<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolesAndPermissionsSeeder extends Seeder
{
    /**
     * @var list<string>
     */
    private array $roles = [
        'Super Admin',
        'Company Admin',
        'Branch Manager',
        'Sales',
        'Designer',
        'Production',
        'Storekeeper',
        'Accountant',
        'HR',
        'Viewer',
    ];

    /**
     * @var list<string>
     */
    private array $permissions = [
        'users.view',
        'users.create',
        'users.edit',
        'users.delete',
        'roles.view',
        'roles.create',
        'roles.edit',
        'roles.delete',
        'security.sessions.view',
        'security.sessions.terminate',
        'security.sessions.force_logout',
        'security.sessions.audit',
        'security.audit.view',
        'security.audit.export',
        'security.audit.manage',
        'companies.manage',
        'branches.manage',
        'departments.manage',
        'employees.manage',
        'hr.attendance.view',
        'hr.attendance.create',
        'hr.attendance.edit',
        'hr.attendance.approve',
        'hr.attendance.export',
        'hr.leave.view',
        'hr.leave.create',
        'hr.leave.approve',
        'hr.leave.reject',
        'hr.leave.export',
        'hr.payroll.view',
        'hr.payroll.process',
        'hr.payroll.approve',
        'hr.payroll.export',
        'hr.documents.view',
        'hr.documents.upload',
        'hr.documents.delete',
        'hr.performance.view',
        'hr.performance.manage',
        'hr.training.view',
        'hr.training.manage',
        'hr.exit.view',
        'hr.exit.manage',
        'hr.dashboard.view',
        'organization.job_titles.view',
        'organization.job_titles.create',
        'organization.job_titles.edit',
        'organization.job_titles.deactivate',
        'activity_logs.view',
        'operations.health.view',
        'operations.health.manage',
        'operations.jobs.view',
        'operations.jobs.retry',
        'operations.jobs.cancel',
        'operations.audit.view',
        'operations.audit.export',
        'operations.backups.view',
        'operations.backups.download',
        'operations.backups.manage',
        'operations.retention.view',
        'operations.retention.manage',
        'governance.chains.view',
        'governance.chains.create',
        'governance.chains.edit',
        'governance.chains.activate',
        'governance.workflow.view',
        'governance.workflow.create',
        'governance.workflow.manage',
        'governance.escalations.view',
        'governance.escalations.manage',
        'crm.customers.view',
        'crm.customers.create',
        'crm.customers.edit',
        'crm.customers.delete',
        'crm.leads.view',
        'crm.leads.create',
        'crm.leads.edit',
        'crm.leads.delete',
        'crm.activities.view',
        'crm.activities.create',
        'crm.activities.edit',
        'crm.activities.delete',
        'quotations.view',
        'quotations.create',
        'quotations.edit',
        'quotations.delete',
        'quotations.approve',
        'quotations.send',
        'quotations.convert',
        'artwork.view',
        'artwork.create',
        'artwork.edit',
        'artwork.delete',
        'artwork.assign',
        'artwork.submit',
        'artwork.approve',
        'sales_orders.view',
        'sales_orders.create',
        'sales_orders.edit',
        'sales_orders.delete',
        'sales_orders.confirm',
        'sales_orders.production',
        'sales_orders.close',
        'pos.view',
        'pos.create',
        'pos.edit',
        'pos.cancel',
        'pos.refund',
        'pos.counter_sales.view',
        'pos.counter_sales.create',
        'pos.counter_sales.hold',
        'pos.counter_sales.complete',
        'pos.counter_sales.cancel',
        'pos.receipts.reprint',
        'pos.sessions.view',
        'pos.sessions.open',
        'pos.sessions.close',
        'pos.sessions.approve_variance',
        'pos.sessions.export',
        'commercial.pos.sessions.view',
        'commercial.pos.sessions.open',
        'commercial.pos.sessions.close',
        'commercial.pos.sessions.audit',
        'commercial.pos.sessions.admin',
        'commercial.pos.reconciliation.view',
        'commercial.pos.reconciliation.create',
        'commercial.pos.reconciliation.approve',
        'commercial.pos.reconciliation.audit',
        'commercial.pos.returns.view',
        'commercial.pos.returns.create',
        'commercial.pos.returns.approve',
        'commercial.pos.returns.audit',
        'commercial.pos.reports.view',
        'commercial.pos.reports.export',
        'commercial.pos.certification.view',
        'commercial.price_books.view',
        'commercial.price_books.create',
        'commercial.price_books.edit',
        'commercial.price_books.delete',
        'commercial.approvals.view',
        'commercial.approvals.action',
        'commercial.complaints.view',
        'commercial.complaints.create',
        'commercial.complaints.edit',
        'commercial.complaints.resolve',
        'commercial.tickets.view',
        'commercial.tickets.create',
        'commercial.tickets.edit',
        'commercial.tickets.assign',
        'commercial.tickets.resolve',
        'production.view',
        'production.create',
        'production.edit',
        'production.delete',
        'production.schedule',
        'production.start',
        'production.complete',
        'production.qc',
        'production.queue.view',
        'production.scheduling.view',
        'production.quality.view',
        'production.work-centers.view',
        'dispatch.view',
        'dispatch.create',
        'dispatch.dispatch',
        'dispatch.deliver',
        'dispatch.cancel',
        'inventory.view',
        'inventory.create',
        'inventory.edit',
        'inventory.delete',
        'inventory.receive',
        'inventory.issue',
        'inventory.adjust',
        'inventory.transfer',
        'catalogue.view',
        'catalogue.create',
        'catalogue.edit',
        'catalogue.delete',
        'procurement.vendors.view',
        'procurement.vendors.create',
        'procurement.vendors.edit',
        'procurement.vendors.delete',
        'procurement.requests.view',
        'procurement.requests.create',
        'procurement.requests.edit',
        'procurement.requests.approve',
        'procurement.requests.delete',
        'procurement.orders.view',
        'procurement.orders.create',
        'procurement.orders.edit',
        'procurement.orders.approve',
        'procurement.orders.receive',
        'procurement.orders.delete',
        'procurement.rfq.view',
        'procurement.rfq.create',
        'procurement.rfq.edit',
        'procurement.comparison.view',
        'procurement.comparison.manage',
        'procurement.vendor_comparison.view',
        'procurement.vendor_comparison.award',
        'procurement.vendor_comparison.manage',
        'procurement.performance.view',
        'procurement.performance.export',
        'inventory.valuation.view',
        'inventory.count.view',
        'inventory.count.create',
        'inventory.count.edit',
        'inventory.count.submit',
        'inventory.count.approve',
        'inventory.count.post',
        'inventory.cycle.view',
        'inventory.cycle.manage',
        'inventory.variance.view',
        'inventory.reconcile.view',
        'inventory.reconcile.approve',
        'inventory.reconcile.post',
        'production.costing.view',
        'production.costing.manage',
        'assets.view',
        'assets.create',
        'assets.edit',
        'assets.manage',
        'settings.view',
        'settings.manage',
        'integrations.view',
        'integrations.manage',
        'integrations.email.manage',
        'integrations.sms.manage',
        'integrations.api.manage',
        'integrations.webhooks.manage',
        'integrations.providers.manage',
        'integrations.audit.view',
        'configuration.document_types.view',
        'configuration.document_types.create',
        'configuration.document_types.edit',
        'configuration.document_types.activate',
        'configuration.document_types.deactivate',
        'governance.delegations.view',
        'governance.delegations.create',
        'governance.delegations.manage',
        'configuration.master_data.view',
        'configuration.master_data.create',
        'configuration.master_data.edit',
        'configuration.master_data.deactivate',
        'configuration.master_data.import',
        'configuration.master_data.export',
        'accounting.chart.view',
        'accounting.chart.create',
        'accounting.chart.edit',
        'accounting.chart.delete',
        'accounting.chart.lock',
        'accounting.periods.view',
        'accounting.periods.create',
        'accounting.periods.manage',
        'accounting.periods.close',
        'accounting.periods.lock',
        'accounting.periods.reopen',
        'accounting.journals.view',
        'accounting.journals.create',
        'accounting.journals.post',
        'accounting.journals.reverse',
        'accounting.posting.view',
        'accounting.posting.manage',
        'accounting.posting_rules.view',
        'accounting.posting_rules.manage',
        'accounting.posting_rules.audit',
        'accounting.reports.view',
        'accounting.dashboard.view',
        'invoices.view',
        'invoices.create',
        'invoices.edit',
        'invoices.delete',
        'invoices.approve',
        'invoices.post',
        'invoices.cancel',
        'invoices.credit_note',
        'payments.view',
        'payments.create',
        'payments.edit',
        'payments.delete',
        'payments.post',
        'payments.cancel',
        'receivables.ledger.view',
        'receivables.statement.view',
        'receivables.aging.view',
        'payables.bills.view',
        'payables.bills.create',
        'payables.bills.edit',
        'payables.bills.delete',
        'payables.bills.approve',
        'payables.bills.post',
        'payables.bills.cancel',
        'payables.bills.credit_note',
        'payables.payments.view',
        'payables.payments.create',
        'payables.payments.edit',
        'payables.payments.delete',
        'payables.payments.post',
        'payables.payments.cancel',
        'payables.ledger.view',
        'payables.statement.view',
        'payables.aging.view',
        'tax.codes.view',
        'tax.codes.manage',
        'tax.reports.view',
        'tax.ledger.view',
        'tax.returns.manage',
        'tax.periods.view',
        'tax.audit.view',
        'communications.templates.view',
        'communications.templates.create',
        'communications.templates.edit',
        'communications.templates.version_view',
        'communications.templates.restore',
        'communications.notifications.view',
        'communications.notifications.manage',
        'communications.notifications.admin',
        'communications.sms.view',
        'communications.sms.send',
        'communications.sms.schedule',
        'communications.sms.approve',
        'communications.sms.audit',
        'communications.logs.view',
        'communications.logs.audit',
        'communications.logs.export',
        'communications.logs.admin',
        'communications.whatsapp.view',
        'communications.whatsapp.send',
        'communications.whatsapp.manage',
        'communications.whatsapp.audit',
        'communications.email.view',
        'communications.email.send',
        'communications.email.schedule',
        'communications.email.manage',
        'communications.email.audit',
        'communications.inbox.view',
        'communications.inbox.reply',
        'communications.inbox.assign',
        'communications.inbox.close',
        'communications.inbox.notes',
        'communications.inbox.attachments',
        'communications.inbox.audit',
        'communications.inbox.escalate',
        'communications.inbox.executive',
        'communications.inbox.admin',
        'reports.view',
        'reports.export',
        'reports.inventory.view',
        'reports.inventory.export',
        'reports.procurement.view',
        'reports.procurement.export',
        'reports.costing.view',
        'reports.costing.export',
        'commercial.reports.sales.view',
        'commercial.reports.sales.export',
        'commercial.reports.sales.manage',
        'commercial.reports.quotations.view',
        'commercial.reports.quotations.export',
        'commercial.reports.sales_orders.view',
        'commercial.reports.sales_orders.export',
        'commercial.reports.customers.view',
        'commercial.reports.customers.export',
        'commercial.reports.artwork.view',
        'commercial.reports.artwork.export',
        'commercial.reports.conversion.view',
        'commercial.reports.conversion.export',
        'commercial.reports.export',
        'commercial.reports.exports.view',
        'commercial.reports.exports.download',
        'kpi.view',
        'kpi.manage',
        'intelligence.inventory.view',
        'intelligence.vendor.view',
        'intelligence.branch.view',
        'intelligence.production.view',
        'intelligence.financial.view',
        'intelligence.commercial.view',
    ];

    /**
     * @var array<string, list<string>>
     */
    private array $rolePermissions = [
        'Company Admin' => [
            'users.view', 'users.create', 'users.edit', 'users.delete',
            'roles.view', 'roles.create', 'roles.edit',
            'branches.manage', 'departments.manage', 'employees.manage',
            'hr.attendance.view', 'hr.attendance.create', 'hr.attendance.edit', 'hr.attendance.approve', 'hr.attendance.export',
            'hr.leave.view', 'hr.leave.create', 'hr.leave.approve', 'hr.leave.reject', 'hr.leave.export',
            'hr.payroll.view', 'hr.payroll.process', 'hr.payroll.approve', 'hr.payroll.export',
            'hr.documents.view', 'hr.documents.upload', 'hr.documents.delete',
            'hr.performance.view', 'hr.performance.manage',
            'hr.training.view', 'hr.training.manage',
            'hr.exit.view', 'hr.exit.manage',
            'hr.dashboard.view',
            'organization.job_titles.view', 'organization.job_titles.create', 'organization.job_titles.edit', 'organization.job_titles.deactivate',
            'activity_logs.view',
            'operations.health.view', 'operations.health.manage',
            'operations.jobs.view', 'operations.jobs.retry', 'operations.jobs.cancel',
            'operations.audit.view', 'operations.audit.export',
            'operations.backups.view', 'operations.backups.download', 'operations.backups.manage',
            'operations.retention.view', 'operations.retention.manage',
            'governance.chains.view', 'governance.chains.create', 'governance.chains.edit', 'governance.chains.activate',
            'governance.workflow.view', 'governance.workflow.create', 'governance.workflow.manage',
            'governance.escalations.view', 'governance.escalations.manage',
            'security.sessions.view', 'security.sessions.terminate', 'security.sessions.force_logout', 'security.sessions.audit',
            'security.audit.view', 'security.audit.export', 'security.audit.manage',
            'crm.customers.view', 'crm.customers.create', 'crm.customers.edit', 'crm.customers.delete',
            'crm.leads.view', 'crm.leads.create', 'crm.leads.edit', 'crm.leads.delete',
            'crm.activities.view', 'crm.activities.create', 'crm.activities.edit', 'crm.activities.delete',
            'quotations.view', 'quotations.create', 'quotations.edit', 'quotations.delete',
            'quotations.approve', 'quotations.send', 'quotations.convert',
            'artwork.view', 'artwork.create', 'artwork.edit', 'artwork.delete',
            'artwork.assign', 'artwork.submit', 'artwork.approve',
            'sales_orders.view', 'sales_orders.create', 'sales_orders.edit', 'sales_orders.delete',
            'sales_orders.confirm', 'sales_orders.production', 'sales_orders.close',
            'pos.view', 'pos.create', 'pos.edit', 'pos.cancel', 'pos.refund',
            'pos.counter_sales.view', 'pos.counter_sales.create', 'pos.counter_sales.hold', 'pos.counter_sales.complete', 'pos.counter_sales.cancel',
            'pos.receipts.reprint',
            'pos.sessions.view', 'pos.sessions.open', 'pos.sessions.close', 'pos.sessions.approve_variance', 'pos.sessions.export',
            'commercial.pos.sessions.view', 'commercial.pos.sessions.open', 'commercial.pos.sessions.close',
            'commercial.pos.sessions.audit', 'commercial.pos.sessions.admin',
            'commercial.pos.reconciliation.view', 'commercial.pos.reconciliation.create',
            'commercial.pos.reconciliation.approve', 'commercial.pos.reconciliation.audit',
            'commercial.pos.returns.view', 'commercial.pos.returns.create', 'commercial.pos.returns.approve', 'commercial.pos.returns.audit',
            'commercial.pos.reports.view', 'commercial.pos.reports.export',
            'commercial.pos.certification.view',
            'production.view', 'production.create', 'production.edit', 'production.delete',
            'production.schedule', 'production.start', 'production.complete', 'production.qc',
            'production.queue.view', 'production.scheduling.view', 'production.quality.view', 'production.work-centers.view',
            'dispatch.view', 'dispatch.create', 'dispatch.dispatch', 'dispatch.deliver', 'dispatch.cancel',
            'inventory.view', 'inventory.create', 'inventory.edit', 'inventory.delete',
            'inventory.receive', 'inventory.issue', 'inventory.adjust', 'inventory.transfer',
            'inventory.count.view', 'inventory.count.create', 'inventory.count.edit',
            'inventory.count.submit', 'inventory.count.approve', 'inventory.count.post',
            'inventory.cycle.view', 'inventory.cycle.manage',
            'inventory.variance.view',
            'inventory.reconcile.view', 'inventory.reconcile.approve', 'inventory.reconcile.post',
            'catalogue.view', 'catalogue.create', 'catalogue.edit', 'catalogue.delete',
            'procurement.vendors.view', 'procurement.vendors.create', 'procurement.vendors.edit', 'procurement.vendors.delete',
            'procurement.requests.view', 'procurement.requests.create', 'procurement.requests.edit', 'procurement.requests.approve', 'procurement.requests.delete',
            'procurement.orders.view', 'procurement.orders.create', 'procurement.orders.edit', 'procurement.orders.approve', 'procurement.orders.receive', 'procurement.orders.delete',
            'procurement.rfq.view', 'procurement.rfq.create', 'procurement.rfq.edit',
            'procurement.comparison.view', 'procurement.comparison.manage',
            'procurement.vendor_comparison.view', 'procurement.vendor_comparison.award', 'procurement.vendor_comparison.manage',
            'procurement.performance.view', 'procurement.performance.export',
            'inventory.valuation.view',
            'production.costing.view', 'production.costing.manage',
            'assets.view', 'assets.create', 'assets.edit', 'assets.manage',
            'settings.view', 'settings.manage',
            'integrations.view', 'integrations.manage',
            'integrations.email.manage', 'integrations.sms.manage',
            'integrations.api.manage', 'integrations.webhooks.manage',
            'integrations.providers.manage', 'integrations.audit.view',
            'configuration.document_types.view', 'configuration.document_types.create',
            'configuration.document_types.edit', 'configuration.document_types.activate', 'configuration.document_types.deactivate',
            'governance.delegations.view', 'governance.delegations.create', 'governance.delegations.manage',
            'configuration.master_data.view', 'configuration.master_data.create', 'configuration.master_data.edit',
            'configuration.master_data.deactivate', 'configuration.master_data.import', 'configuration.master_data.export',
            'accounting.chart.view', 'accounting.chart.create', 'accounting.chart.edit', 'accounting.chart.delete', 'accounting.chart.lock',
            'accounting.periods.view', 'accounting.periods.create', 'accounting.periods.manage', 'accounting.periods.close', 'accounting.periods.lock', 'accounting.periods.reopen',
            'accounting.journals.view', 'accounting.journals.create', 'accounting.journals.post', 'accounting.journals.reverse',
            'accounting.posting.view', 'accounting.posting.manage',
            'accounting.posting_rules.view', 'accounting.posting_rules.manage', 'accounting.posting_rules.audit',
            'accounting.reports.view',
            'accounting.dashboard.view',
            'invoices.view', 'invoices.create', 'invoices.edit', 'invoices.delete', 'invoices.approve', 'invoices.post', 'invoices.cancel', 'invoices.credit_note',
            'payments.view', 'payments.create', 'payments.edit', 'payments.delete', 'payments.post', 'payments.cancel',
            'receivables.ledger.view', 'receivables.statement.view', 'receivables.aging.view',
            'payables.bills.view', 'payables.bills.create', 'payables.bills.edit', 'payables.bills.delete', 'payables.bills.approve', 'payables.bills.post', 'payables.bills.cancel', 'payables.bills.credit_note',
            'payables.payments.view', 'payables.payments.create', 'payables.payments.edit', 'payables.payments.delete', 'payables.payments.post', 'payables.payments.cancel',
            'payables.ledger.view', 'payables.statement.view', 'payables.aging.view',
            'tax.codes.view', 'tax.codes.manage', 'tax.reports.view', 'tax.ledger.view', 'tax.returns.manage', 'tax.periods.view', 'tax.audit.view',
            'communications.templates.view', 'communications.templates.create', 'communications.templates.edit', 'communications.templates.version_view', 'communications.templates.restore',
            'communications.notifications.view', 'communications.notifications.manage', 'communications.notifications.admin',
            'communications.sms.view', 'communications.sms.send', 'communications.sms.schedule', 'communications.sms.approve', 'communications.sms.audit',
            'communications.logs.view', 'communications.logs.audit', 'communications.logs.export', 'communications.logs.admin',
            'communications.whatsapp.view', 'communications.whatsapp.send', 'communications.whatsapp.manage', 'communications.whatsapp.audit',
            'communications.email.view', 'communications.email.send', 'communications.email.schedule', 'communications.email.manage', 'communications.email.audit',
            'communications.inbox.view', 'communications.inbox.reply', 'communications.inbox.assign', 'communications.inbox.close', 'communications.inbox.notes', 'communications.inbox.attachments', 'communications.inbox.audit', 'communications.inbox.escalate', 'communications.inbox.executive', 'communications.inbox.admin',
            'reports.view', 'reports.export', 'reports.inventory.view', 'reports.inventory.export', 'reports.procurement.view', 'reports.procurement.export', 'reports.costing.view', 'reports.costing.export', 'kpi.view', 'kpi.manage',
            'commercial.reports.sales.view', 'commercial.reports.sales.export', 'commercial.reports.sales.manage',
            'commercial.reports.quotations.view', 'commercial.reports.quotations.export',
            'commercial.reports.sales_orders.view', 'commercial.reports.sales_orders.export',
            'commercial.reports.customers.view', 'commercial.reports.customers.export',
            'commercial.reports.artwork.view', 'commercial.reports.artwork.export',
            'commercial.reports.conversion.view', 'commercial.reports.conversion.export',
            'commercial.reports.export', 'commercial.reports.exports.view', 'commercial.reports.exports.download',
            'commercial.price_books.view', 'commercial.price_books.create', 'commercial.price_books.edit', 'commercial.price_books.delete',
            'commercial.approvals.view', 'commercial.approvals.action',
            'commercial.complaints.view', 'commercial.complaints.create', 'commercial.complaints.edit', 'commercial.complaints.resolve',
            'commercial.tickets.view', 'commercial.tickets.create', 'commercial.tickets.edit', 'commercial.tickets.assign', 'commercial.tickets.resolve',
            'intelligence.inventory.view', 'intelligence.vendor.view', 'intelligence.branch.view',
            'intelligence.production.view', 'intelligence.financial.view', 'intelligence.commercial.view',
        ],
        'Branch Manager' => [
            'users.view', 'users.edit',
            'branches.manage', 'departments.manage', 'employees.manage',
            'hr.attendance.view', 'hr.attendance.create', 'hr.attendance.edit', 'hr.attendance.approve', 'hr.attendance.export',
            'hr.leave.view', 'hr.leave.create', 'hr.leave.approve', 'hr.leave.reject', 'hr.leave.export',
            'hr.payroll.view', 'hr.payroll.process', 'hr.payroll.approve', 'hr.payroll.export',
            'hr.documents.view', 'hr.documents.upload', 'hr.documents.delete',
            'hr.performance.view', 'hr.performance.manage',
            'hr.training.view', 'hr.training.manage',
            'hr.exit.view', 'hr.exit.manage',
            'hr.dashboard.view',
            'organization.job_titles.view', 'organization.job_titles.create', 'organization.job_titles.edit', 'organization.job_titles.deactivate',
            'activity_logs.view', 'security.sessions.view',
            'crm.customers.view', 'crm.customers.create', 'crm.customers.edit',
            'crm.leads.view', 'crm.leads.create', 'crm.leads.edit',
            'crm.activities.view', 'crm.activities.create', 'crm.activities.edit',
            'quotations.view', 'quotations.create', 'quotations.edit', 'quotations.approve', 'quotations.send',
            'artwork.view', 'artwork.create', 'artwork.edit', 'artwork.assign', 'artwork.approve',
            'sales_orders.view', 'sales_orders.create', 'sales_orders.edit', 'sales_orders.confirm',
            'pos.view', 'pos.create', 'pos.edit', 'pos.cancel',
            'pos.counter_sales.view', 'pos.counter_sales.create', 'pos.counter_sales.hold', 'pos.counter_sales.complete', 'pos.counter_sales.cancel',
            'pos.receipts.reprint',
            'pos.sessions.view', 'pos.sessions.open', 'pos.sessions.close', 'pos.sessions.approve_variance', 'pos.sessions.export',
            'commercial.pos.sessions.view', 'commercial.pos.sessions.open', 'commercial.pos.sessions.close', 'commercial.pos.sessions.audit',
            'commercial.pos.reconciliation.view', 'commercial.pos.reconciliation.create',
            'commercial.pos.reconciliation.approve', 'commercial.pos.reconciliation.audit',
            'commercial.pos.returns.view', 'commercial.pos.returns.create', 'commercial.pos.returns.approve',
            'commercial.pos.reports.view', 'commercial.pos.reports.export',
            'commercial.pos.certification.view',
            'settings.view',
            'catalogue.view',
            'communications.notifications.view',
            'communications.notifications.manage',
            'communications.whatsapp.view', 'communications.whatsapp.send',
            'communications.email.view', 'communications.email.send',
            'communications.inbox.view', 'communications.inbox.reply', 'communications.inbox.assign', 'communications.inbox.notes', 'communications.inbox.escalate',
            'reports.view', 'reports.inventory.view', 'reports.inventory.export', 'reports.procurement.view', 'reports.procurement.export',
            'procurement.performance.view', 'procurement.performance.export',
            'commercial.reports.sales.view', 'commercial.reports.sales.export',
            'commercial.reports.quotations.view', 'commercial.reports.quotations.export',
            'commercial.reports.sales_orders.view', 'commercial.reports.sales_orders.export',
            'commercial.reports.customers.view', 'commercial.reports.customers.export',
            'commercial.reports.artwork.view', 'commercial.reports.artwork.export',
            'commercial.reports.conversion.view', 'commercial.reports.conversion.export',
            'commercial.reports.export', 'commercial.reports.exports.view', 'commercial.reports.exports.download',
            'commercial.price_books.view', 'commercial.price_books.create', 'commercial.price_books.edit',
            'commercial.approvals.view', 'commercial.approvals.action',
            'commercial.complaints.view', 'commercial.complaints.create', 'commercial.complaints.edit', 'commercial.complaints.resolve',
            'commercial.tickets.view', 'commercial.tickets.create', 'commercial.tickets.edit', 'commercial.tickets.assign', 'commercial.tickets.resolve',
            'inventory.count.view', 'inventory.count.create', 'inventory.count.submit',
            'inventory.cycle.view', 'inventory.reconcile.view',
            'inventory.variance.view',
        ],
        'Sales' => [
            'crm.customers.view', 'crm.customers.create', 'crm.customers.edit',
            'crm.leads.view', 'crm.leads.create', 'crm.leads.edit',
            'crm.activities.view', 'crm.activities.create', 'crm.activities.edit',
            'quotations.view', 'quotations.create', 'quotations.edit', 'quotations.send',
            'artwork.view', 'artwork.create',
            'quotations.convert',
            'sales_orders.view', 'sales_orders.create', 'sales_orders.edit', 'sales_orders.confirm',
            'pos.view', 'pos.create', 'pos.edit', 'pos.cancel',
            'pos.counter_sales.view', 'pos.counter_sales.create', 'pos.counter_sales.hold', 'pos.counter_sales.complete', 'pos.counter_sales.cancel',
            'pos.receipts.reprint',
            'pos.sessions.view', 'pos.sessions.open', 'pos.sessions.close',
            'commercial.pos.sessions.view', 'commercial.pos.sessions.open',
            'commercial.pos.reconciliation.view', 'commercial.pos.reconciliation.create',
            'commercial.pos.returns.view', 'commercial.pos.returns.create',
            'commercial.pos.reports.view',
            'catalogue.view',
            'invoices.view', 'invoices.create', 'invoices.edit', 'invoices.approve',
            'payments.view', 'payments.create', 'payments.edit',
            'communications.notifications.view',
            'communications.notifications.manage',
            'communications.whatsapp.view', 'communications.whatsapp.send',
            'communications.email.view', 'communications.email.send',
            'commercial.reports.sales.view',
            'commercial.reports.quotations.view',
            'commercial.reports.sales_orders.view',
            'commercial.reports.customers.view',
            'commercial.reports.artwork.view',
            'commercial.reports.conversion.view',
            'commercial.price_books.view',
            'commercial.approvals.view',
            'commercial.complaints.view', 'commercial.complaints.create',
            'commercial.tickets.view', 'commercial.tickets.create',
        ],
        'Production' => [
            'sales_orders.view', 'sales_orders.production',
            'production.view', 'production.create', 'production.edit',
            'production.schedule', 'production.start', 'production.complete', 'production.qc',
            'production.queue.view', 'production.scheduling.view', 'production.quality.view', 'production.work-centers.view',
            'dispatch.view', 'dispatch.create', 'dispatch.dispatch', 'dispatch.deliver',
            'production.costing.view',
            'reports.costing.view',
            'inventory.view', 'inventory.issue',
            'catalogue.view',
            'procurement.requests.view', 'procurement.requests.create',
            'procurement.orders.view',
            'communications.notifications.view',
            'communications.notifications.manage',
        ],
        'Storekeeper' => [
            'inventory.view', 'inventory.create', 'inventory.edit',
            'inventory.receive', 'inventory.issue', 'inventory.adjust', 'inventory.transfer',
            'inventory.count.view', 'inventory.count.create', 'inventory.count.edit', 'inventory.count.submit',
            'inventory.cycle.view', 'inventory.cycle.manage',
            'inventory.variance.view',
            'inventory.reconcile.view',
            'catalogue.view', 'catalogue.create', 'catalogue.edit',
            'procurement.vendors.view',
            'procurement.requests.view', 'procurement.requests.create',
            'procurement.orders.view', 'procurement.orders.receive',
            'procurement.rfq.view', 'procurement.comparison.view', 'procurement.vendor_comparison.view',
            'inventory.valuation.view',
            'reports.inventory.view',
            'reports.procurement.view',
            'reports.procurement.export',
            'procurement.performance.view',
            'procurement.performance.export',
        ],
        'Designer' => [
            'artwork.view', 'artwork.edit', 'artwork.submit',
            'commercial.reports.artwork.view',
        ],
        'Viewer' => [
            'users.view', 'roles.view', 'activity_logs.view', 'security.sessions.view',
            'configuration.master_data.view', 'security.audit.view',
            'accounting.posting_rules.audit',
            'communications.templates.view', 'communications.templates.version_view',
            'communications.notifications.view',
            'communications.logs.view',
            'communications.whatsapp.view',
            'communications.email.view',
            'communications.inbox.view',
            'crm.customers.view', 'crm.leads.view', 'crm.activities.view',
            'quotations.view',
            'artwork.view',
            'sales_orders.view',
            'production.view',
            'inventory.view',
            'catalogue.view',
            'procurement.vendors.view', 'procurement.requests.view', 'procurement.orders.view',
            'reports.view',
        ],
        'Accountant' => [
            'crm.customers.view',
            'quotations.view',
            'sales_orders.view',
            'inventory.view',
            'catalogue.view',
            'procurement.vendors.view', 'procurement.orders.view',
            'inventory.valuation.view',
            'inventory.variance.view',
            'inventory.reconcile.view',
            'assets.view',
            'activity_logs.view',
            'settings.view',
            'accounting.chart.view', 'accounting.chart.create', 'accounting.chart.edit', 'accounting.chart.lock',
            'accounting.periods.view', 'accounting.periods.create', 'accounting.periods.close', 'accounting.periods.lock', 'accounting.periods.reopen',
            'accounting.journals.view', 'accounting.journals.create', 'accounting.journals.post', 'accounting.journals.reverse',
            'accounting.posting.view', 'accounting.posting.manage',
            'accounting.posting_rules.view', 'accounting.posting_rules.manage', 'accounting.posting_rules.audit',
            'accounting.reports.view',
            'accounting.dashboard.view',
            'invoices.view', 'invoices.create', 'invoices.edit', 'invoices.approve', 'invoices.post', 'invoices.cancel', 'invoices.credit_note',
            'payments.view', 'payments.create', 'payments.edit', 'payments.post',
            'receivables.ledger.view', 'receivables.statement.view', 'receivables.aging.view',
            'payables.bills.view', 'payables.bills.create', 'payables.bills.edit', 'payables.bills.approve', 'payables.bills.post', 'payables.bills.cancel', 'payables.bills.credit_note',
            'payables.payments.view', 'payables.payments.create', 'payables.payments.edit', 'payables.payments.post', 'payables.payments.cancel',
            'payables.ledger.view', 'payables.statement.view', 'payables.aging.view',
            'tax.codes.view', 'tax.codes.manage', 'tax.reports.view', 'tax.ledger.view', 'tax.returns.manage', 'tax.periods.view', 'tax.audit.view',
            'reports.view', 'reports.export',
        ],
        'HR' => [
            'users.view', 'users.create', 'users.edit',
            'employees.manage',
            'hr.attendance.view', 'hr.attendance.create', 'hr.attendance.edit', 'hr.attendance.approve', 'hr.attendance.export',
            'hr.leave.view', 'hr.leave.create', 'hr.leave.approve', 'hr.leave.reject', 'hr.leave.export',
            'hr.payroll.view', 'hr.payroll.process', 'hr.payroll.approve', 'hr.payroll.export',
            'hr.documents.view', 'hr.documents.upload', 'hr.documents.delete',
            'hr.performance.view', 'hr.performance.manage',
            'hr.training.view', 'hr.training.manage',
            'hr.exit.view', 'hr.exit.manage',
            'hr.dashboard.view',
            'departments.manage',
            'branches.manage',
            'organization.job_titles.view', 'organization.job_titles.create', 'organization.job_titles.edit', 'organization.job_titles.deactivate',
            'activity_logs.view',
            'reports.view', 'reports.inventory.view',
            'kpi.view',
        ],
    ];

    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        foreach ($this->permissions as $permission) {
            Permission::findOrCreate($permission, 'web');
        }

        foreach ($this->roles as $roleName) {
            Role::findOrCreate($roleName, 'web');
        }

        $superAdmin = Role::findByName('Super Admin', 'web');
        $superAdmin->syncPermissions($this->permissions);

        foreach ($this->rolePermissions as $roleName => $permissions) {
            $role = Role::findByName($roleName, 'web');
            $role->syncPermissions($permissions);
        }
    }
}
