<?php if(! empty($paymentFooter)): ?>
    <div class="jp-doc__payment-footer">
        <table class="jp-doc__payment-footer-table" cellpadding="0" cellspacing="0">
            <tr>
                <td class="jp-doc__payment-footer-left">
                    <p class="jp-doc__payment-footer-title"><?php echo e(__('Payment Details')); ?>:</p>
                    <?php $__currentLoopData = $paymentFooter; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $line): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                        <p class="jp-doc__payment-footer-line"><?php echo e($line); ?></p>
                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                </td>
                <td class="jp-doc__payment-footer-right">
                    <p class="jp-doc__footer-thanks"><?php echo e($documentFooter['thanks'] ?? __('Thank you for choosing Jana Prints.')); ?></p>
                    <p class="jp-doc__footer-system"><?php echo e($documentFooter['system'] ?? __('This document was generated by Jana Prints ERP.')); ?></p>
                </td>
            </tr>
        </table>
    </div>
<?php endif; ?>
<?php /**PATH C:\xampp\htdocs\jana-prints\resources\views\documents\partials\payment-footer.blade.php ENDPATH**/ ?>