<div class="jp-doc__footer">
    <p class="jp-doc__footer-thanks"><?php echo e($documentFooter['thanks'] ?? __('Thank you for choosing Jana Prints.')); ?></p>
    <p class="jp-doc__footer-system"><?php echo e($documentFooter['system'] ?? __('This document was generated by Jana Prints ERP.')); ?></p>
</div>
<?php /**PATH C:\xampp\htdocs\jana-prints\resources\views\documents\partials\footer.blade.php ENDPATH**/ ?>