<?php

/**
 * Assets workspace hub catalog (presentation only).
 */
return [

    'groups' => [
        [
            'label' => 'Asset Management',
            'items' => [
                [
                    'label' => 'Asset Management',
                    'description' => 'Register, categories, and KPIs in one workspace.',
                    'route' => 'admin.assets.index',
                    'permission' => 'assets.view',
                    'icon' => 'chip',
                    'count_key' => 'register',
                    'active_routes' => [
                        'admin.assets.index',
                        'admin.assets.dashboard',
                        'admin.assets.categories.index',
                        'admin.assets.categories.*',
                        'admin.assets.show',
                        'admin.assets.create',
                        'admin.assets.edit',
                        'admin.assets.store',
                        'admin.assets.update',
                    ],
                    'toolbar_actions' => [
                        [
                            'label' => 'Register asset',
                            'route' => 'admin.assets.create',
                            'permission' => 'assets.create',
                            'modal' => true,
                        ],
                        [
                            'label' => 'New category',
                            'route' => 'admin.assets.categories.create',
                            'permission' => 'assets.categories.manage',
                            'modal' => true,
                        ],
                    ],
                ],
                [
                    'label' => 'Machines',
                    'description' => 'Production machines — availability, utilization, and assignments.',
                    'route' => 'admin.assets.machines.index',
                    'permission' => 'machines.view',
                    'icon' => 'cog',
                    'count_key' => 'machines',
                    'active_routes' => ['admin.assets.machines.index', 'admin.assets.machines.dashboard', 'admin.assets.machines.create', 'admin.assets.machines.show'],
                ],
            ],
        ],
        [
            'label' => 'Maintenance',
            'items' => [
                [
                    'label' => 'Maintenance Dashboard',
                    'description' => 'Work orders, downtime, and maintenance KPIs.',
                    'route' => 'admin.assets.maintenance.dashboard',
                    'permission' => 'maintenance.view',
                    'icon' => 'chart-pie',
                    'count_key' => 'maintenance_open',
                    'active_routes' => ['admin.assets.maintenance.dashboard'],
                ],
                [
                    'label' => 'Work Orders',
                    'description' => 'Preventive, corrective, and emergency maintenance.',
                    'route' => 'admin.assets.maintenance.work-orders.index',
                    'permission' => 'maintenance.view',
                    'icon' => 'clipboard-list',
                    'active_routes' => ['admin.assets.maintenance.work-orders.*'],
                ],
                [
                    'label' => 'Maintenance Plans',
                    'description' => 'Preventive maintenance schedules.',
                    'route' => 'admin.assets.maintenance.plans.index',
                    'permission' => 'maintenance.view',
                    'icon' => 'calendar',
                    'active_routes' => ['admin.assets.maintenance.plans.*'],
                ],
                [
                    'label' => 'Maintenance Calendar',
                    'description' => 'Month, week, upcoming, and overdue views.',
                    'route' => 'admin.assets.maintenance.calendar',
                    'permission' => 'maintenance.calendar.view',
                    'icon' => 'calendar',
                    'active_routes' => ['admin.assets.maintenance.calendar'],
                ],
                [
                    'label' => 'Downtime',
                    'description' => 'Asset downtime records and impact.',
                    'route' => 'admin.assets.maintenance.downtime.index',
                    'permission' => 'maintenance.view',
                    'icon' => 'pause',
                    'active_routes' => ['admin.assets.maintenance.downtime.*'],
                ],
                [
                    'label' => 'Technicians',
                    'description' => 'Internal and vendor maintenance technicians.',
                    'route' => 'admin.assets.maintenance.technicians.index',
                    'permission' => 'maintenance.view',
                    'icon' => 'user',
                    'active_routes' => ['admin.assets.maintenance.technicians.*'],
                ],
            ],
        ],
        [
            'label' => 'Custody',
            'items' => [
                [
                    'label' => 'Custody Dashboard',
                    'description' => 'Assignments, transfers, returns, and accountability KPIs.',
                    'route' => 'admin.assets.custody.dashboard',
                    'permission' => 'assets.custody.view',
                    'icon' => 'chart-pie',
                    'count_key' => 'custody_pending',
                    'active_routes' => ['admin.assets.custody.dashboard'],
                ],
                [
                    'label' => 'Assignments',
                    'description' => 'Employee and department asset assignments.',
                    'route' => 'admin.assets.custody.assignments.index',
                    'permission' => 'assets.custody.view',
                    'icon' => 'user',
                    'active_routes' => ['admin.assets.custody.assignments.*'],
                ],
                [
                    'label' => 'Handovers',
                    'description' => 'Formal asset handover records.',
                    'route' => 'admin.assets.custody.handovers.index',
                    'permission' => 'assets.custody.view',
                    'icon' => 'switch-horizontal',
                    'count_key' => 'custody_handovers',
                    'active_routes' => ['admin.assets.custody.handovers.*'],
                ],
                [
                    'label' => 'Returns',
                    'description' => 'Asset return workflow and condition capture.',
                    'route' => 'admin.assets.custody.returns.index',
                    'permission' => 'assets.custody.view',
                    'icon' => 'arrow-left',
                    'active_routes' => ['admin.assets.custody.returns.*'],
                ],
                [
                    'label' => 'Branch Transfers',
                    'description' => 'Branch-to-branch asset transfers.',
                    'route' => 'admin.assets.custody.transfers.index',
                    'permission' => 'assets.custody.view',
                    'icon' => 'office-building',
                    'count_key' => 'custody_transfers',
                    'active_routes' => ['admin.assets.custody.transfers.*'],
                ],
            ],
        ],
        [
            'label' => 'Finance',
            'items' => [
                [
                    'label' => 'Asset Finance Dashboard',
                    'description' => 'Asset cost, NBV, and depreciation KPIs.',
                    'route' => 'admin.assets.finance.dashboard',
                    'permission' => 'assets.depreciation.view',
                    'icon' => 'chart-pie',
                    'active_routes' => ['admin.assets.finance.dashboard'],
                ],
                [
                    'label' => 'Depreciation Runs',
                    'description' => 'Company-wide monthly depreciation execution.',
                    'route' => 'admin.assets.finance.runs.index',
                    'permission' => 'assets.depreciation.view',
                    'icon' => 'calendar',
                    'active_routes' => ['admin.assets.finance.runs.*'],
                ],
                [
                    'label' => 'Depreciation Entries',
                    'description' => 'Posted and draft depreciation register.',
                    'route' => 'admin.assets.finance.entries.index',
                    'permission' => 'assets.depreciation.view',
                    'icon' => 'clipboard-list',
                    'active_routes' => ['admin.assets.finance.entries.*'],
                ],
                [
                    'label' => 'Reconciliation',
                    'description' => 'Asset register vs general ledger.',
                    'route' => 'admin.assets.finance.reconciliation.index',
                    'permission' => 'assets.reconciliation.view',
                    'icon' => 'scale',
                    'active_routes' => ['admin.assets.finance.reconciliation.*'],
                ],
                [
                    'label' => 'Asset Reports',
                    'description' => 'Register, valuation, and depreciation reports.',
                    'route' => 'admin.assets.finance.reports.index',
                    'permission' => 'assets.depreciation.view',
                    'icon' => 'document-report',
                    'active_routes' => ['admin.assets.finance.reports.*'],
                ],
                [
                    'label' => 'Write-Offs',
                    'description' => 'Damaged, lost, and obsolete asset write-offs.',
                    'route' => 'admin.assets.finance.write-offs.index',
                    'permission' => 'assets.depreciation.view',
                    'icon' => 'exclamation',
                    'active_routes' => ['admin.assets.finance.write-offs.*'],
                ],
            ],
        ],
        [
            'label' => 'Acquisitions',
            'items' => [
                [
                    'label' => 'Acquisition Dashboard',
                    'description' => 'Pending capitalization and procurement asset KPIs.',
                    'route' => 'admin.assets.acquisitions.dashboard',
                    'permission' => 'assets.acquisition.view',
                    'icon' => 'chart-pie',
                    'active_routes' => ['admin.assets.acquisitions.dashboard'],
                ],
                [
                    'label' => 'Capitalization Queue',
                    'description' => 'Received asset purchases awaiting capitalization.',
                    'route' => 'admin.assets.acquisitions.queue',
                    'permission' => 'assets.acquisition.view',
                    'icon' => 'inbox',
                    'count_key' => 'capitalization_pending',
                    'active_routes' => ['admin.assets.acquisitions.queue', 'admin.assets.acquisitions.workbench'],
                ],
                [
                    'label' => 'Warranty Center',
                    'description' => 'Asset warranty profiles and expiry tracking.',
                    'route' => 'admin.assets.acquisitions.warranties',
                    'permission' => 'assets.acquisition.view',
                    'icon' => 'shield-check',
                    'active_routes' => ['admin.assets.acquisitions.warranties.*'],
                ],
                [
                    'label' => 'Capitalization Reconciliation',
                    'description' => 'Procurement, accounting, and asset register alignment.',
                    'route' => 'admin.assets.acquisitions.reconciliation.index',
                    'permission' => 'assets.reconciliation.view',
                    'icon' => 'scale',
                    'active_routes' => ['admin.assets.acquisitions.reconciliation.*'],
                ],
            ],
        ],
        [
            'label' => 'Intelligence',
            'items' => [
                [
                    'label' => 'Executive Asset Dashboard',
                    'description' => 'Company-wide asset valuation and risk KPIs.',
                    'route' => 'admin.assets.intelligence.executive',
                    'permission' => 'assets.analytics.view',
                    'icon' => 'chart-pie',
                    'active_routes' => ['admin.assets.intelligence.executive'],
                ],
                [
                    'label' => 'Branch Asset Intelligence',
                    'description' => 'Per-branch asset profile and utilization.',
                    'route' => 'admin.assets.intelligence.branch',
                    'permission' => 'assets.analytics.view',
                    'icon' => 'office-building',
                    'active_routes' => ['admin.assets.intelligence.branch'],
                ],
                [
                    'label' => 'Asset Analytics Center',
                    'description' => 'Trends, distributions, and lifecycle analytics.',
                    'route' => 'admin.assets.intelligence.analytics',
                    'permission' => 'assets.analytics.view',
                    'icon' => 'chart-bar',
                    'active_routes' => ['admin.assets.intelligence.analytics'],
                ],
                [
                    'label' => 'Asset 360',
                    'description' => 'Open any asset and select View 360 for complete lifecycle intelligence.',
                    'route' => 'admin.assets.index',
                    'permission' => 'assets.360.view',
                    'icon' => 'sparkles',
                    'active_routes' => ['admin.assets.360.show'],
                ],
                [
                    'label' => 'Asset Reports',
                    'description' => 'Register, valuation, depreciation, maintenance, and custody reports.',
                    'route' => 'admin.assets.finance.reports.index',
                    'permission' => 'assets.depreciation.view',
                    'icon' => 'document-report',
                    'active_routes' => ['admin.assets.finance.reports.*'],
                ],
            ],
        ],
    ],

];
