<?php

$i = require __DIR__ . '/public-images.php';

return [

    'capabilities' => [
        [
            'slug' => 'corporate-printing',
            'number' => '01',
            'title' => 'Corporate Printing',
            'description' => 'Premium stationery and corporate documents that represent your brand with precision — from first impression business cards to polished annual reports.',
            'items' => [
                'Business Cards',
                'Letterheads',
                'Envelopes',
                'Company Profiles',
                'Annual Reports',
                'Brochures',
                'Presentation Folders',
            ],
            'image' => $i['stationery'],
            'alt' => 'Premium corporate stationery including letterheads, business cards and presentation folders',
            'accent' => 'from-brand-magenta to-brand-purple',
            'portfolio_filter' => 'corporate-stationery',
            'highlights' => [
                ['label' => 'What we produce', 'value' => 'Full corporate stationery suites'],
                ['label' => 'Typical turnaround', 'value' => '2–5 business days'],
                ['label' => 'Minimum quantities', 'value' => 'From 100 units'],
                ['label' => 'Design support', 'value' => 'Available'],
                ['label' => 'Delivery', 'value' => 'Nationwide'],
            ],
        ],
        [
            'slug' => 'marketing-materials',
            'number' => '02',
            'title' => 'Marketing Materials',
            'description' => 'Vivid, campaign-ready print that drives attention — flyers, catalogues, menus, and promotional inserts produced at scale with consistent colour.',
            'items' => [
                'Flyers',
                'Posters',
                'Catalogues',
                'Leaflets',
                'Menus',
                'Product Sheets',
                'Promotional Inserts',
            ],
            'image' => $i['brochure'],
            'alt' => 'Colourful marketing print materials including brochures, flyers and catalogues',
            'accent' => 'from-brand-orange to-brand-magenta',
            'portfolio_filter' => 'flyers',
            'highlights' => [
                ['label' => 'What we produce', 'value' => 'Campaign & retail collateral'],
                ['label' => 'Typical turnaround', 'value' => '1–4 business days'],
                ['label' => 'Minimum quantities', 'value' => 'From 250 units'],
                ['label' => 'Design support', 'value' => 'Available'],
                ['label' => 'Delivery', 'value' => 'Nationwide'],
            ],
        ],
        [
            'slug' => 'packaging-labels',
            'number' => '03',
            'title' => 'Packaging & Labels',
            'description' => 'Custom packaging and labels that protect your product and elevate your brand on the shelf — from retail boxes to food-safe packaging.',
            'items' => [
                'Product Packaging',
                'Custom Boxes',
                'Labels',
                'Stickers',
                'Retail Packaging',
                'Food Packaging',
            ],
            'image' => $i['packaging'],
            'alt' => 'Custom product packaging boxes and retail label printing',
            'accent' => 'from-brand-purple to-brand-cyan',
            'portfolio_filter' => 'packaging',
            'highlights' => [
                ['label' => 'What we produce', 'value' => 'Boxes, labels & retail packs'],
                ['label' => 'Typical turnaround', 'value' => '5–10 business days'],
                ['label' => 'Minimum quantities', 'value' => 'From 500 units'],
                ['label' => 'Design support', 'value' => 'Available'],
                ['label' => 'Delivery', 'value' => 'Nationwide'],
            ],
        ],
        [
            'slug' => 'large-format',
            'number' => '04',
            'title' => 'Large Format Printing',
            'description' => 'High-impact signage and displays that command attention — banners, billboards, backdrops, and event graphics built for durability and vivid colour.',
            'items' => [
                'Banners',
                'Roll-Up Banners',
                'Billboards',
                'Backdrops',
                'Window Graphics',
                'Event Signage',
            ],
            'image' => $i['banner'],
            'alt' => 'Large format roll-up banners and event signage installations',
            'accent' => 'from-brand-cyan to-brand-purple',
            'portfolio_filter' => 'large-format',
            'highlights' => [
                ['label' => 'What we produce', 'value' => 'Indoor & outdoor signage'],
                ['label' => 'Typical turnaround', 'value' => '2–6 business days'],
                ['label' => 'Minimum quantities', 'value' => 'From 1 unit'],
                ['label' => 'Design support', 'value' => 'Available'],
                ['label' => 'Delivery', 'value' => 'Nationwide + install options'],
            ],
        ],
        [
            'slug' => 'branding-solutions',
            'number' => '05',
            'title' => 'Branding Solutions',
            'description' => 'End-to-end brand environments — vehicle wraps, office branding, wall graphics, and corporate identity systems that unify your presence.',
            'items' => [
                'Vehicle Branding',
                'Office Branding',
                'Wall Graphics',
                'Reception Branding',
                'Directional Signage',
                'Corporate Identity Systems',
            ],
            'image' => $i['vehicle'],
            'alt' => 'Vehicle branding and corporate office identity installations',
            'accent' => 'from-brand-navy to-brand-magenta',
            'portfolio_filter' => 'vehicle-branding',
            'highlights' => [
                ['label' => 'What we produce', 'value' => 'Full brand environment rollouts'],
                ['label' => 'Typical turnaround', 'value' => '7–14 business days'],
                ['label' => 'Minimum quantities', 'value' => 'Project-based'],
                ['label' => 'Design support', 'value' => 'Included'],
                ['label' => 'Delivery', 'value' => 'On-site installation available'],
            ],
        ],
        [
            'slug' => 'promotional-merchandise',
            'number' => '06',
            'title' => 'Promotional Merchandise',
            'description' => 'Branded merchandise that keeps your name in hand — mugs, apparel, pens, bags, and corporate gift items for events, campaigns, and client gifting.',
            'items' => [
                'Branded Mugs',
                'T-Shirts',
                'Pens',
                'Bags',
                'Gift Items',
                'Corporate Merchandise',
            ],
            'image' => $i['merchandise'],
            'alt' => 'Branded promotional merchandise including mugs, bags and corporate gift items',
            'accent' => 'from-brand-orange to-brand-cyan',
            'portfolio_filter' => 'promotional-materials',
            'highlights' => [
                ['label' => 'What we produce', 'value' => 'Branded promo & corporate gifts'],
                ['label' => 'Typical turnaround', 'value' => '5–10 business days'],
                ['label' => 'Minimum quantities', 'value' => 'From 50 units'],
                ['label' => 'Design support', 'value' => 'Available'],
                ['label' => 'Delivery', 'value' => 'Nationwide'],
            ],
        ],
    ],

    'trust_points' => [
        'Quality Checked',
        'Artwork Approval',
        'Production Tracking',
        'Professional Finishing',
    ],

];
