<?php

return [

    'settings_groups' => [
        'company' => 'Company Details',
        'payment' => 'Payment Details',
        'terms' => 'Document Terms',
        'footer' => 'Footer Messages',
        'labels' => 'Document Labels',
    ],

    'settings_admin_tabs' => [
        'company' => 'Company',
        'payment' => 'Payment',
        'terms' => 'Terms',
        'footer' => 'Footer',
        'labels' => 'Labels',
    ],

    'settings' => [
        'company.name' => [
            'group' => 'company',
            'type' => 'string',
            'admin_tab' => 'company',
            'label' => 'Company name',
            'description' => 'Printed on quotations, invoices, and receipts when the company record has no name.',
            'fallback_config' => 'documents.company.name',
            'optional' => true,
        ],
        'company.address' => [
            'group' => 'company',
            'type' => 'string',
            'admin_tab' => 'company',
            'label' => 'Address',
            'description' => 'Mailing or physical address shown on commercial documents.',
            'fallback_config' => 'documents.company.address',
            'optional' => true,
        ],
        'company.phone' => [
            'group' => 'company',
            'type' => 'phone',
            'admin_tab' => 'company',
            'label' => 'Phone',
            'description' => 'Primary contact phone printed on documents.',
            'fallback_config' => 'documents.company.phone',
            'optional' => true,
        ],
        'company.email' => [
            'group' => 'company',
            'type' => 'email',
            'admin_tab' => 'company',
            'label' => 'Email',
            'description' => 'Contact email printed on documents.',
            'fallback_config' => 'documents.company.email',
            'optional' => true,
        ],
        'company.website' => [
            'group' => 'company',
            'type' => 'string',
            'admin_tab' => 'company',
            'label' => 'Website',
            'description' => 'Website URL or domain shown on documents (https:// optional).',
            'fallback_config' => 'documents.company.website',
            'optional' => true,
        ],

        'payment.mpesa_paybill' => [
            'group' => 'payment',
            'type' => 'string',
            'admin_tab' => 'payment',
            'label' => 'M-Pesa Paybill number',
            'description' => 'Paybill number shown in the payment footer.',
            'fallback_config' => 'documents.payment.mpesa_paybill',
            'optional' => true,
        ],
        'payment.mpesa_account' => [
            'group' => 'payment',
            'type' => 'string',
            'admin_tab' => 'payment',
            'label' => 'M-Pesa account number',
            'description' => 'Account number customers should use when paying via Paybill.',
            'fallback_config' => 'documents.payment.mpesa_account',
            'optional' => true,
        ],
        'payment.cheque_payable_to' => [
            'group' => 'payment',
            'type' => 'string',
            'admin_tab' => 'payment',
            'label' => 'Cheques payable to',
            'description' => 'Legal payee name for cheque payments.',
            'fallback_config' => 'documents.payment.cheque_payable_to',
            'optional' => true,
        ],
        'payment.bank_name' => [
            'group' => 'payment',
            'type' => 'string',
            'admin_tab' => 'payment',
            'label' => 'Bank name',
            'description' => 'Bank name for transfer instructions.',
            'fallback_config' => 'documents.payment.bank_name',
            'optional' => true,
        ],
        'payment.bank_branch' => [
            'group' => 'payment',
            'type' => 'string',
            'admin_tab' => 'payment',
            'label' => 'Bank branch',
            'description' => 'Branch name for transfer instructions.',
            'fallback_config' => 'documents.payment.bank_branch',
            'optional' => true,
        ],
        'payment.bank_account_name' => [
            'group' => 'payment',
            'type' => 'string',
            'admin_tab' => 'payment',
            'label' => 'Bank account name',
            'description' => 'Account holder name for bank transfers.',
            'fallback_config' => 'documents.payment.bank_account_name',
            'optional' => true,
        ],
        'payment.bank_account' => [
            'group' => 'payment',
            'type' => 'string',
            'admin_tab' => 'payment',
            'label' => 'Bank account number',
            'description' => 'Account number for bank transfers.',
            'fallback_config' => 'documents.payment.bank_account',
            'optional' => true,
        ],

        'terms.quotation' => [
            'group' => 'terms',
            'type' => 'text',
            'admin_tab' => 'terms',
            'label' => 'Quotation terms',
            'description' => 'Default terms paragraph printed on quotations.',
            'fallback_config' => 'documents.terms.quotation',
            'optional' => true,
        ],
        'terms.invoice' => [
            'group' => 'terms',
            'type' => 'text',
            'admin_tab' => 'terms',
            'label' => 'Invoice terms',
            'description' => 'Default terms paragraph printed on invoices.',
            'fallback_config' => 'documents.terms.invoice',
            'optional' => true,
        ],
        'terms.receipt' => [
            'group' => 'terms',
            'type' => 'text',
            'admin_tab' => 'terms',
            'label' => 'Receipt acknowledgement',
            'description' => 'Optional acknowledgement text for payment receipts when no payment notes exist.',
            'fallback_config' => 'documents.terms.receipt_acknowledgement',
            'optional' => true,
        ],

        'footer.thanks' => [
            'group' => 'footer',
            'type' => 'string',
            'admin_tab' => 'footer',
            'label' => 'Thank-you message',
            'description' => 'Short thank-you line in the purple document footer.',
            'fallback_config' => 'document_cms.defaults.footer.thanks',
            'optional' => true,
        ],
        'footer.system' => [
            'group' => 'footer',
            'type' => 'string',
            'admin_tab' => 'footer',
            'label' => 'System line',
            'description' => 'Small attribution line below the thank-you message.',
            'fallback_config' => 'document_cms.defaults.footer.system',
            'optional' => true,
        ],

        'labels.tax' => [
            'group' => 'labels',
            'type' => 'string',
            'admin_tab' => 'labels',
            'label' => 'Tax total label',
            'description' => 'Label shown on document totals for tax (e.g. VAT / Tax).',
            'fallback_config' => 'document_cms.defaults.labels.tax',
            'optional' => true,
        ],
    ],

    'defaults' => [
        'footer' => [
            'thanks' => 'Thank you for choosing Jana Prints.',
            'system' => 'This document was generated by Jana Prints ERP.',
        ],
        'labels' => [
            'tax' => 'VAT / Tax',
        ],
    ],

];
