<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Governed document type definitions (Phase CFG-2)
    |--------------------------------------------------------------------------
    |
    | Each entry seeds a company-scoped document type definition. The
    | number_series_key links to numbering_sequences.document_type when set.
    | approval_rule_type links to approval_registry.rule_types when set.
    |
    */

    'types' => [

        'quotation' => [
            'name' => 'Quotation',
            'module' => 'commercial',
            'prefix' => 'QUOTE',
            'number_series_key' => 'quotation',
            'approval_required' => true,
            'approval_levels' => 2,
            'approval_rule_type' => 'quotation_approval',
            'retention_period_days' => 2555,
            'auto_numbering' => true,
            'form_key' => 'quotation',
            'workflow' => [
                'approval_workflow' => 'quotation_approval',
                'notification_workflow' => 'quotation_status',
                'audit_tracking' => true,
                'archival_rules' => 'standard_commercial',
                'print_template' => 'quotation_default',
            ],
        ],

        'sales_order' => [
            'name' => 'Sales Order',
            'module' => 'commercial',
            'prefix' => 'SO',
            'number_series_key' => 'sales_order',
            'approval_required' => false,
            'approval_levels' => 0,
            'approval_rule_type' => null,
            'retention_period_days' => 2555,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'sales_order_status',
                'audit_tracking' => true,
                'archival_rules' => 'standard_commercial',
                'print_template' => 'sales_order_default',
            ],
        ],

        'invoice' => [
            'name' => 'Invoice',
            'module' => 'commercial',
            'prefix' => 'INV',
            'number_series_key' => 'invoice',
            'approval_required' => true,
            'approval_levels' => 1,
            'approval_rule_type' => null,
            'retention_period_days' => 3650,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'invoice_posted',
                'audit_tracking' => true,
                'archival_rules' => 'financial_records',
                'print_template' => 'invoice_default',
            ],
        ],

        'credit_note' => [
            'name' => 'Credit Note',
            'module' => 'commercial',
            'prefix' => 'CN',
            'number_series_key' => 'credit_note',
            'approval_required' => true,
            'approval_levels' => 1,
            'approval_rule_type' => null,
            'retention_period_days' => 3650,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'credit_note_posted',
                'audit_tracking' => true,
                'archival_rules' => 'financial_records',
                'print_template' => 'credit_note_default',
            ],
        ],

        'receipt' => [
            'name' => 'Receipt',
            'module' => 'commercial',
            'prefix' => 'RCPT',
            'number_series_key' => 'payment',
            'approval_required' => false,
            'approval_levels' => 0,
            'approval_rule_type' => null,
            'retention_period_days' => 2555,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'payment_received',
                'audit_tracking' => true,
                'archival_rules' => 'financial_records',
                'print_template' => 'receipt_default',
            ],
        ],

        'artwork_request' => [
            'name' => 'Artwork Request',
            'module' => 'production',
            'prefix' => 'ART',
            'number_series_key' => 'artwork_request',
            'approval_required' => false,
            'approval_levels' => 0,
            'approval_rule_type' => null,
            'retention_period_days' => 1825,
            'auto_numbering' => true,
            'form_key' => 'artwork',
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'artwork_assigned',
                'audit_tracking' => true,
                'archival_rules' => 'production_records',
                'print_template' => 'artwork_request_default',
            ],
        ],

        'artwork_approval' => [
            'name' => 'Artwork Approval',
            'module' => 'production',
            'prefix' => 'ARTA',
            'number_series_key' => null,
            'approval_required' => true,
            'approval_levels' => 1,
            'approval_rule_type' => null,
            'retention_period_days' => 1825,
            'auto_numbering' => false,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => 'artwork_approval',
                'notification_workflow' => 'artwork_approved',
                'audit_tracking' => true,
                'archival_rules' => 'production_records',
                'print_template' => null,
            ],
        ],

        'job_card' => [
            'name' => 'Job Card',
            'module' => 'production',
            'prefix' => 'JOB',
            'number_series_key' => 'job_card',
            'approval_required' => false,
            'approval_levels' => 0,
            'approval_rule_type' => null,
            'retention_period_days' => 1825,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'job_card_status',
                'audit_tracking' => true,
                'archival_rules' => 'production_records',
                'print_template' => 'job_card_default',
            ],
        ],

        'quality_inspection' => [
            'name' => 'Quality Inspection',
            'module' => 'production',
            'prefix' => 'QC',
            'number_series_key' => null,
            'approval_required' => true,
            'approval_levels' => 1,
            'approval_rule_type' => null,
            'retention_period_days' => 1825,
            'auto_numbering' => false,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => 'quality_inspection',
                'notification_workflow' => 'qc_completed',
                'audit_tracking' => true,
                'archival_rules' => 'production_records',
                'print_template' => 'qc_report_default',
            ],
        ],

        'purchase_request' => [
            'name' => 'Purchase Request',
            'module' => 'supply_chain',
            'prefix' => 'PR',
            'number_series_key' => 'purchase_request',
            'approval_required' => true,
            'approval_levels' => 1,
            'approval_rule_type' => null,
            'retention_period_days' => 1825,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'purchase_request_submitted',
                'audit_tracking' => true,
                'archival_rules' => 'procurement_records',
                'print_template' => 'purchase_request_default',
            ],
        ],

        'purchase_order' => [
            'name' => 'Purchase Order',
            'module' => 'supply_chain',
            'prefix' => 'PO',
            'number_series_key' => 'purchase_order',
            'approval_required' => true,
            'approval_levels' => 2,
            'approval_rule_type' => 'procurement_approval',
            'retention_period_days' => 2555,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => 'procurement_approval',
                'notification_workflow' => 'purchase_order_approved',
                'audit_tracking' => true,
                'archival_rules' => 'procurement_records',
                'print_template' => 'purchase_order_default',
            ],
        ],

        'goods_receipt' => [
            'name' => 'Goods Receipt',
            'module' => 'supply_chain',
            'prefix' => 'GRN',
            'number_series_key' => 'goods_receipt',
            'approval_required' => false,
            'approval_levels' => 0,
            'approval_rule_type' => null,
            'retention_period_days' => 1825,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'goods_receipt_posted',
                'audit_tracking' => true,
                'archival_rules' => 'procurement_records',
                'print_template' => 'goods_receipt_default',
            ],
        ],

        'vendor_invoice' => [
            'name' => 'Vendor Invoice',
            'module' => 'supply_chain',
            'prefix' => 'VBILL',
            'number_series_key' => 'supplier_bill',
            'approval_required' => true,
            'approval_levels' => 1,
            'approval_rule_type' => null,
            'retention_period_days' => 3650,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'vendor_invoice_posted',
                'audit_tracking' => true,
                'archival_rules' => 'financial_records',
                'print_template' => 'vendor_invoice_default',
            ],
        ],

        'stock_adjustment' => [
            'name' => 'Stock Adjustment',
            'module' => 'inventory',
            'prefix' => 'ADJ',
            'number_series_key' => 'stock_adjustment',
            'approval_required' => true,
            'approval_levels' => 1,
            'approval_rule_type' => 'stock_adjustment_approval',
            'retention_period_days' => 1825,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => 'stock_adjustment_approval',
                'notification_workflow' => 'stock_adjustment_posted',
                'audit_tracking' => true,
                'archival_rules' => 'inventory_records',
                'print_template' => 'stock_adjustment_default',
            ],
        ],

        'stock_transfer' => [
            'name' => 'Stock Transfer',
            'module' => 'inventory',
            'prefix' => 'XFER',
            'number_series_key' => 'stock_issue',
            'approval_required' => false,
            'approval_levels' => 0,
            'approval_rule_type' => null,
            'retention_period_days' => 1825,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'stock_transfer_completed',
                'audit_tracking' => true,
                'archival_rules' => 'inventory_records',
                'print_template' => 'stock_transfer_default',
            ],
        ],

        'cycle_count' => [
            'name' => 'Cycle Count',
            'module' => 'inventory',
            'prefix' => 'CC',
            'number_series_key' => null,
            'approval_required' => true,
            'approval_levels' => 1,
            'approval_rule_type' => null,
            'retention_period_days' => 1095,
            'auto_numbering' => false,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'cycle_count_variance',
                'audit_tracking' => true,
                'archival_rules' => 'inventory_records',
                'print_template' => 'cycle_count_default',
            ],
        ],

        'journal_entry' => [
            'name' => 'Journal Entry',
            'module' => 'accounting',
            'prefix' => 'JE',
            'number_series_key' => 'journal',
            'approval_required' => true,
            'approval_levels' => 1,
            'approval_rule_type' => null,
            'retention_period_days' => 3650,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'journal_posted',
                'audit_tracking' => true,
                'archival_rules' => 'financial_records',
                'print_template' => 'journal_entry_default',
            ],
        ],

        'payment_voucher' => [
            'name' => 'Payment Voucher',
            'module' => 'accounting',
            'prefix' => 'PV',
            'number_series_key' => 'supplier_payment',
            'approval_required' => true,
            'approval_levels' => 2,
            'approval_rule_type' => 'payment_approval',
            'retention_period_days' => 3650,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => 'payment_approval',
                'notification_workflow' => 'payment_voucher_posted',
                'audit_tracking' => true,
                'archival_rules' => 'financial_records',
                'print_template' => 'payment_voucher_default',
            ],
        ],

        'receipt_voucher' => [
            'name' => 'Receipt Voucher',
            'module' => 'accounting',
            'prefix' => 'RV',
            'number_series_key' => 'payment',
            'approval_required' => false,
            'approval_levels' => 0,
            'approval_rule_type' => null,
            'retention_period_days' => 3650,
            'auto_numbering' => true,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'receipt_voucher_posted',
                'audit_tracking' => true,
                'archival_rules' => 'financial_records',
                'print_template' => 'receipt_voucher_default',
            ],
        ],

        'employee_record' => [
            'name' => 'Employee Record',
            'module' => 'hr',
            'prefix' => 'EMP',
            'number_series_key' => null,
            'approval_required' => false,
            'approval_levels' => 0,
            'approval_rule_type' => null,
            'retention_period_days' => 3650,
            'auto_numbering' => false,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => null,
                'notification_workflow' => 'employee_onboarded',
                'audit_tracking' => true,
                'archival_rules' => 'hr_records',
                'print_template' => null,
            ],
        ],

        'leave_request' => [
            'name' => 'Leave Request',
            'module' => 'hr',
            'prefix' => 'LV',
            'number_series_key' => null,
            'approval_required' => true,
            'approval_levels' => 1,
            'approval_rule_type' => null,
            'retention_period_days' => 1825,
            'auto_numbering' => false,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => 'leave_approval',
                'notification_workflow' => 'leave_status',
                'audit_tracking' => true,
                'archival_rules' => 'hr_records',
                'print_template' => null,
            ],
        ],

        'disciplinary_record' => [
            'name' => 'Disciplinary Record',
            'module' => 'hr',
            'prefix' => 'DISC',
            'number_series_key' => null,
            'approval_required' => true,
            'approval_levels' => 2,
            'approval_rule_type' => null,
            'retention_period_days' => 3650,
            'auto_numbering' => false,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => 'disciplinary_approval',
                'notification_workflow' => 'disciplinary_filed',
                'audit_tracking' => true,
                'archival_rules' => 'hr_confidential',
                'print_template' => null,
            ],
        ],

        'sms_campaign' => [
            'name' => 'SMS Campaign',
            'module' => 'communications',
            'prefix' => 'SMS',
            'number_series_key' => null,
            'approval_required' => true,
            'approval_levels' => 1,
            'approval_rule_type' => null,
            'retention_period_days' => 365,
            'auto_numbering' => false,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => 'communications_approval',
                'notification_workflow' => 'sms_campaign_scheduled',
                'audit_tracking' => true,
                'archival_rules' => 'communications_records',
                'print_template' => null,
            ],
        ],

        'email_campaign' => [
            'name' => 'Email Campaign',
            'module' => 'communications',
            'prefix' => 'EML',
            'number_series_key' => null,
            'approval_required' => true,
            'approval_levels' => 1,
            'approval_rule_type' => null,
            'retention_period_days' => 365,
            'auto_numbering' => false,
            'form_key' => null,
            'workflow' => [
                'approval_workflow' => 'communications_approval',
                'notification_workflow' => 'email_campaign_scheduled',
                'audit_tracking' => true,
                'archival_rules' => 'communications_records',
                'print_template' => 'email_campaign_default',
            ],
        ],

    ],

];
