<?php

$i = require __DIR__ . '/public-images.php';

return [

    'filters' => [
        ['slug' => 'all', 'label' => 'All'],
        ['slug' => 'business-cards', 'label' => 'Business Cards'],
        ['slug' => 'corporate-stationery', 'label' => 'Corporate Stationery'],
        ['slug' => 'brochures', 'label' => 'Brochures'],
        ['slug' => 'flyers', 'label' => 'Flyers'],
        ['slug' => 'packaging', 'label' => 'Packaging'],
        ['slug' => 'large-format', 'label' => 'Large Format'],
        ['slug' => 'vehicle-branding', 'label' => 'Vehicle Branding'],
        ['slug' => 'promotional-materials', 'label' => 'Promotional Materials'],
        ['slug' => 'events-exhibitions', 'label' => 'Events & Exhibitions'],
    ],

    'stats' => [
        ['value' => 5000, 'suffix' => '+', 'label' => 'Projects Delivered'],
        ['value' => 1200, 'suffix' => '+', 'label' => 'Customers'],
        ['value' => 100, 'suffix' => '+', 'label' => 'Large Format Jobs'],
        ['value' => 98, 'suffix' => '%', 'label' => 'On-Time Completion'],
    ],

    'featured' => [
        [
            'title' => 'Corporate Rebrand Campaign',
            'highlights' => [
                '5,000 brochures',
                '500 business cards',
                '30 roll-up banners',
                'Completed in 5 days',
            ],
            'image' => $i['corporate'],
            'alt' => 'Corporate rebrand print campaign with brochures and business cards',
        ],
        [
            'title' => 'School Prospectus Production',
            'highlights' => [
                '15,000 copies',
                'Design + printing',
                'Nationwide distribution',
            ],
            'image' => $i['school'],
            'alt' => 'School prospectus printing and binding project',
        ],
        [
            'title' => 'Retail Packaging Launch',
            'highlights' => [
                'Packaging design',
                'Label printing',
                'Point-of-sale materials',
            ],
            'image' => $i['packaging'],
            'alt' => 'Retail product packaging and label printing',
        ],
    ],

    'projects' => [
        [
            'id' => 'corporate-business-cards-nairobi',
            'title' => 'Corporate Business Cards',
            'category' => 'business-cards',
            'category_label' => 'Business Cards',
            'location' => 'Nairobi',
            'quantity' => '2,500 cards',
            'layout' => 'hero',
            'image' => $i['cards'],
            'alt' => 'Premium corporate business cards with matte lamination produced in Nairobi',
            'description' => 'Full corporate business card run for a financial services firm — double-sided colour, spot UV logo, and rounded corners on premium 350gsm stock.',
            'materials' => '350gsm art card, matte lamination, spot UV',
            'timeline' => '3 business days',
            'outcome' => 'Consistent brand reproduction across all staff cards with zero colour variance between batches.',
        ],
        [
            'id' => 'ngo-annual-report-nakuru',
            'title' => 'NGO Annual Report',
            'category' => 'brochures',
            'category_label' => 'Brochures',
            'location' => 'Nakuru',
            'quantity' => '3,000 copies',
            'layout' => 'tall',
            'image' => $i['brochure'],
            'alt' => 'NGO annual report brochure printing in Nakuru',
            'description' => 'Annual impact report with full-colour photography, perfect binding, and a soft-touch cover for donor distribution.',
            'materials' => '170gsm inner pages, 300gsm cover, soft-touch laminate',
            'timeline' => '7 days',
            'outcome' => 'Delivered ahead of the NGO\'s annual general meeting with approved proofs signed off digitally.',
        ],
        [
            'id' => 'school-prospectus-eldoret',
            'title' => 'School Prospectus Printing',
            'category' => 'brochures',
            'category_label' => 'Brochures',
            'location' => 'Eldoret',
            'quantity' => '8,000 copies',
            'layout' => 'normal',
            'image' => $i['school'],
            'alt' => 'School prospectus design and print run in Eldoret',
            'description' => 'Complete prospectus production for a private school — layout, pre-press, saddle-stitch binding, and bulk delivery.',
            'materials' => '128gsm gloss art paper, saddle-stitch binding',
            'timeline' => '5 days',
            'outcome' => 'High-quality enrolment collateral distributed to partner schools across the Rift Valley.',
        ],
        [
            'id' => 'product-packaging-mombasa',
            'title' => 'Product Packaging',
            'category' => 'packaging',
            'category_label' => 'Packaging',
            'location' => 'Mombasa',
            'quantity' => '10,000 units',
            'layout' => 'wide',
            'image' => $i['packaging'],
            'alt' => 'Custom product packaging boxes printed in Mombasa',
            'description' => 'Retail-ready product boxes with custom die-cut structure, CMYK print, and gloss finish for a coastal FMCG brand launch.',
            'materials' => '350gsm folding carton, gloss laminate',
            'timeline' => '10 days',
            'outcome' => 'Packaging passed retail shelf-ready inspection and supported a successful coastal market launch.',
        ],
        [
            'id' => 'corporate-stationery-kisumu',
            'title' => 'Corporate Stationery Suite',
            'category' => 'corporate-stationery',
            'category_label' => 'Corporate Stationery',
            'location' => 'Kisumu',
            'quantity' => 'Full brand suite',
            'layout' => 'normal',
            'image' => $i['stationery'],
            'alt' => 'Corporate letterheads envelopes and folders printed in Kisumu',
            'description' => 'Letterheads, compliment slips, envelopes, and presentation folders for a regional corporate headquarters.',
            'materials' => '100gsm bond, 300gsm folder stock, embossing',
            'timeline' => '4 days',
            'outcome' => 'Unified stationery system deployed across three regional offices with matched brand colours.',
        ],
        [
            'id' => 'election-campaign-flyers',
            'title' => 'Campaign Flyer Run',
            'category' => 'flyers',
            'category_label' => 'Flyers',
            'location' => 'Nairobi',
            'quantity' => '50,000 flyers',
            'layout' => 'tall',
            'image' => $i['flyers'],
            'alt' => 'High-volume campaign flyer printing in Nairobi',
            'description' => 'High-volume A5 flyer production with tight colour consistency across a 50,000-piece campaign print run.',
            'materials' => '128gsm gloss art, single-sided CMYK',
            'timeline' => '2 days',
            'outcome' => 'Rush delivery met campaign launch deadline with full colour matching across all sheets.',
        ],
        [
            'id' => 'exhibition-rollup-banners',
            'title' => 'Exhibition Roll-Up Banners',
            'category' => 'events-exhibitions',
            'category_label' => 'Events & Exhibitions',
            'location' => 'Nairobi',
            'quantity' => '24 banners',
            'layout' => 'wide',
            'image' => $i['banner'],
            'alt' => 'Roll-up banner stands for corporate exhibition in Nairobi',
            'description' => 'Premium roll-up banners with aluminium stands for a multi-day trade exhibition — vivid colour and durable base units.',
            'materials' => 'PP banner material, aluminium roll-up stands',
            'timeline' => '3 days',
            'outcome' => 'All stands delivered assembled and ready for booth setup on the morning of the event.',
        ],
        [
            'id' => 'fleet-vehicle-branding',
            'title' => 'Fleet Vehicle Branding',
            'category' => 'vehicle-branding',
            'category_label' => 'Vehicle Branding',
            'location' => 'Nairobi',
            'quantity' => '12 vehicles',
            'layout' => 'hero',
            'image' => $i['vehicle'],
            'alt' => 'Commercial fleet vehicle branding and vinyl wraps in Nairobi',
            'description' => 'Full fleet branding programme — partial wraps, door decals, and bonnet logos for a logistics company\'s delivery vans.',
            'materials' => 'Cast vinyl, UV laminate, reflective accents',
            'timeline' => '14 days',
            'outcome' => 'Fleet transformed into mobile brand ambassadors with durable graphics rated for highway use.',
        ],
        [
            'id' => 'hotel-promotional-materials',
            'title' => 'Hospitality Promo Pack',
            'category' => 'promotional-materials',
            'category_label' => 'Promotional Materials',
            'location' => 'Mombasa',
            'quantity' => 'Mixed collateral',
            'layout' => 'normal',
            'image' => $i['merchandise'],
            'alt' => 'Promotional print materials for hospitality brand in Mombasa',
            'description' => 'Branded menus, coasters, tent cards, and welcome brochures for a coastal hospitality group relaunch.',
            'materials' => '300gsm board, waterproof menu stock, die-cut coasters',
            'timeline' => '6 days',
            'outcome' => 'Complete promo pack delivered to three hotel properties before the grand reopening weekend.',
        ],
        [
            'id' => 'building-wrap-large-format',
            'title' => 'Building Facade Wrap',
            'category' => 'large-format',
            'category_label' => 'Large Format',
            'location' => 'Nairobi',
            'quantity' => '120 sqm',
            'layout' => 'tall',
            'image' => $i['print_press'],
            'alt' => 'Large format building facade wrap printing in Nairobi',
            'description' => 'Massive-format building wrap for a construction site — weather-resistant mesh material with high-resolution brand artwork.',
            'materials' => 'Mesh banner material, reinforced eyelets, UV ink',
            'timeline' => '5 days',
            'outcome' => 'High-visibility branding installed on schedule with vivid colour visible from major road traffic.',
        ],
        [
            'id' => 'conference-materials',
            'title' => 'Conference Delegate Pack',
            'category' => 'events-exhibitions',
            'category_label' => 'Events & Exhibitions',
            'location' => 'Nakuru',
            'quantity' => '800 delegates',
            'layout' => 'normal',
            'image' => $i['banner'],
            'alt' => 'Conference delegate materials and programme printing in Nakuru',
            'description' => 'Delegate folders, programmes, lanyard inserts, and name badges for a regional industry conference.',
            'materials' => '300gsm folders, 128gsm programme, PVC badge stock',
            'timeline' => '4 days',
            'outcome' => 'Every delegate received a complete branded pack at registration with zero missing items.',
        ],
        [
            'id' => 'event-backdrop-printing',
            'title' => 'Event Backdrop Printing',
            'category' => 'large-format',
            'category_label' => 'Large Format',
            'location' => 'Nairobi',
            'quantity' => '1 backdrop',
            'layout' => 'wide',
            'image' => $i['event'],
            'alt' => 'Large format event backdrop and stage branding printing in Nairobi',
            'description' => 'Stage backdrop and step-and-repeat banner for a corporate gala — seamless brand artwork at event scale.',
            'materials' => 'PVC flex, aluminium frame, UV print',
            'timeline' => '4 days',
            'outcome' => 'Backdrop installed on-site with crisp colour visible in photography and livestream coverage.',
        ],
        [
            'id' => 'startup-business-cards',
            'title' => 'Startup Brand Launch Cards',
            'category' => 'business-cards',
            'category_label' => 'Business Cards',
            'location' => 'Nairobi',
            'quantity' => '1,000 cards',
            'layout' => 'normal',
            'image' => $i['cards'],
            'alt' => 'Startup business card printing with premium finish in Nairobi',
            'description' => 'Launch-day business cards for a tech startup — minimalist design with soft-touch laminate and painted edges.',
            'materials' => '400gsm black core card, soft-touch laminate',
            'timeline' => '2 days',
            'outcome' => 'Cards delivered in time for the startup\'s investor pitch event the same week.',
        ],
    ],

];
