<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Settings Control Center — business domain catalog (SET-3A)
    |--------------------------------------------------------------------------
    |
    | Navigation and grouping only. Card links resolve to existing settings
    | routes and admin pages without changing underlying services.
    |
    */

    'domains' => [

        'organization' => [
            'label' => 'Organization',
            'description' => 'Company administration, structure, and access governance.',
            'cards' => [
                [
                    'id' => 'company-profile',
                    'title' => 'Company Profile',
                    'description' => 'Legal identity, defaults, and organization-wide preferences.',
                    'icon' => 'building',
                    'keywords' => ['company', 'profile', 'legal', 'organization'],
                    'link' => ['type' => 'settings', 'section' => 'company'],
                    'status' => ['type' => 'registry', 'section' => 'company'],
                ],
                [
                    'id' => 'branches',
                    'title' => 'Branches',
                    'description' => 'Branch locations, display names, and document contact details.',
                    'icon' => 'office-building',
                    'keywords' => ['branch', 'location', 'office', 'site'],
                    'link' => ['type' => 'settings', 'section' => 'branch'],
                    'status' => ['type' => 'registry', 'section' => 'branch'],
                ],
                [
                    'id' => 'departments',
                    'title' => 'Departments',
                    'description' => 'Organizational units used for reporting and access grouping.',
                    'icon' => 'collection',
                    'keywords' => ['department', 'division', 'unit', 'team'],
                    'link' => ['type' => 'route', 'name' => 'admin.departments.index'],
                    'status' => ['type' => 'departments'],
                ],
                [
                    'id' => 'users',
                    'title' => 'Users',
                    'description' => 'User accounts, branch assignment, and login access.',
                    'icon' => 'users',
                    'keywords' => ['user', 'account', 'login', 'employee access'],
                    'link' => ['type' => 'route', 'name' => 'admin.users.index'],
                    'status' => ['type' => 'users'],
                ],
                [
                    'id' => 'roles-access',
                    'title' => 'Roles & Access',
                    'description' => 'Manage user roles, security groups, and permission governance.',
                    'icon' => 'shield-check',
                    'keywords' => ['role', 'access', 'permission', 'security', 'governance'],
                    'link' => ['type' => 'route', 'name' => 'admin.access-control.index'],
                    'status' => ['type' => 'roles'],
                ],
                [
                    'id' => 'document-branding',
                    'title' => 'Document Branding',
                    'description' => 'Logos, letterheads, and branded document templates.',
                    'icon' => 'photograph',
                    'keywords' => ['branding', 'logo', 'letterhead', 'template', 'favicon'],
                    'link' => ['type' => 'route', 'name' => 'admin.settings.branding.edit'],
                    'status' => ['type' => 'branding'],
                ],
                [
                    'id' => 'commercial-documents',
                    'title' => 'Commercial Documents',
                    'description' => 'Payment instructions, company details, terms, and footer text on invoices and quotations.',
                    'icon' => 'document-text',
                    'keywords' => ['invoice', 'quotation', 'receipt', 'mpesa', 'bank', 'payment', 'footer'],
                    'link' => ['type' => 'route', 'name' => 'admin.documents.settings.index'],
                    'status' => ['type' => 'route', 'name' => 'admin.documents.settings.index'],
                ],
            ],
        ],

        'sales' => [
            'label' => 'Sales',
            'description' => 'Customer-facing workflows from lead to order.',
            'cards' => [
                [
                    'id' => 'crm',
                    'title' => 'CRM',
                    'description' => 'Lead follow-ups, customer requirements, and conversion rules.',
                    'icon' => 'users',
                    'keywords' => ['crm', 'lead', 'pipeline', 'customer relationship'],
                    'link' => ['type' => 'settings', 'section' => 'crm'],
                    'status' => ['type' => 'registry', 'section' => 'crm'],
                ],
                [
                    'id' => 'quotations',
                    'title' => 'Quotations',
                    'description' => 'Validity periods, approval requirements, and pricing controls.',
                    'icon' => 'document-text',
                    'keywords' => ['quotation', 'quote', 'pricing', 'validity', 'discount'],
                    'link' => ['type' => 'settings', 'section' => 'quotation'],
                    'status' => ['type' => 'registry', 'section' => 'quotation'],
                ],
                [
                    'id' => 'sales-orders',
                    'title' => 'Sales Orders',
                    'description' => 'Order confirmation, deposits, and job card generation rules.',
                    'icon' => 'shopping-cart',
                    'keywords' => ['sales order', 'order', 'confirmation', 'deposit'],
                    'link' => ['type' => 'settings', 'section' => 'sales-order'],
                    'status' => ['type' => 'registry', 'section' => 'sales-order'],
                ],
                [
                    'id' => 'customers',
                    'title' => 'Customers',
                    'description' => 'Customer master defaults, segments, and credit policies.',
                    'icon' => 'user-circle',
                    'keywords' => ['customer', 'account', 'credit', 'segment'],
                    'coming_soon' => true,
                ],
                [
                    'id' => 'discount-policies',
                    'title' => 'Discount Policies',
                    'description' => 'Discount limits, tiers, and approval thresholds for sales.',
                    'icon' => 'tag',
                    'keywords' => ['discount', 'pricing', 'margin', 'approval'],
                    'link' => ['type' => 'settings', 'section' => 'quotation'],
                    'status' => ['type' => 'registry', 'section' => 'quotation'],
                ],
                [
                    'id' => 'customer-defaults',
                    'title' => 'Customer Defaults',
                    'description' => 'Default payment terms, tax treatment, and delivery preferences.',
                    'icon' => 'identification',
                    'keywords' => ['customer', 'default', 'payment terms', 'delivery'],
                    'link' => ['type' => 'settings', 'section' => 'crm'],
                    'status' => ['type' => 'registry', 'section' => 'crm'],
                ],
            ],
        ],

        'production' => [
            'label' => 'Production',
            'description' => 'Artwork, manufacturing workflow, and job execution controls.',
            'cards' => [
                [
                    'id' => 'artwork-workflow',
                    'title' => 'Artwork Workflow',
                    'description' => 'Artwork requests, customer approval, and designer assignment.',
                    'icon' => 'color-swatch',
                    'keywords' => ['artwork', 'design', 'proof', 'approval'],
                    'link' => ['type' => 'settings', 'section' => 'artwork'],
                    'status' => ['type' => 'registry', 'section' => 'artwork'],
                ],
                [
                    'id' => 'production-workflow',
                    'title' => 'Production Workflow',
                    'description' => 'Configure stages, status transitions, and production controls.',
                    'icon' => 'chip',
                    'keywords' => ['production', 'workflow', 'stage', 'status', 'manufacturing'],
                    'link' => ['type' => 'settings', 'section' => 'production'],
                    'status' => ['type' => 'registry', 'section' => 'production'],
                ],
                [
                    'id' => 'machine-configuration',
                    'title' => 'Machine Configuration',
                    'description' => 'Presses, finishing equipment, and production capacity setup.',
                    'icon' => 'cog',
                    'keywords' => ['machine', 'press', 'equipment', 'capacity'],
                    'coming_soon' => true,
                ],
                [
                    'id' => 'job-scheduling',
                    'title' => 'Job Scheduling',
                    'description' => 'Scheduling rules, priorities, and capacity planning defaults.',
                    'icon' => 'calendar',
                    'keywords' => ['scheduling', 'job', 'priority', 'planning', 'production'],
                    'link' => ['type' => 'settings', 'section' => 'production'],
                    'status' => ['type' => 'registry', 'section' => 'production'],
                ],
                [
                    'id' => 'production-approvals',
                    'title' => 'Production Approvals',
                    'description' => 'Approval thresholds for production changes and releases.',
                    'icon' => 'shield-check',
                    'keywords' => ['production', 'approval', 'release', 'sign-off'],
                    'link' => ['type' => 'route', 'name' => 'admin.settings.approvals.index'],
                    'status' => ['type' => 'approvals'],
                ],
                [
                    'id' => 'job-numbering',
                    'title' => 'Job Numbering',
                    'description' => 'Prefixes and sequences for job cards and production documents.',
                    'icon' => 'template',
                    'keywords' => ['job', 'numbering', 'sequence', 'prefix', 'job card'],
                    'link' => ['type' => 'route', 'name' => 'admin.settings.numbering.index'],
                    'status' => ['type' => 'numbering'],
                ],
            ],
        ],

        'inventory' => [
            'label' => 'Inventory',
            'description' => 'Stock control, warehousing, and inventory governance.',
            'cards' => [
                [
                    'id' => 'warehouses',
                    'title' => 'Warehouses',
                    'description' => 'Warehouse locations, bins, and storage structure.',
                    'icon' => 'archive',
                    'keywords' => ['warehouse', 'storage', 'location', 'bin'],
                    'link' => ['type' => 'route', 'name' => 'admin.inventory.warehouses.index'],
                ],
                [
                    'id' => 'inventory-categories',
                    'title' => 'Inventory Categories',
                    'description' => 'Material groups, product families, and stock classification.',
                    'icon' => 'view-grid',
                    'keywords' => ['category', 'classification', 'material', 'product group'],
                    'link' => ['type' => 'route', 'name' => 'admin.inventory.catalogue.categories.index'],
                ],
                [
                    'id' => 'units-of-measure',
                    'title' => 'Units of Measure',
                    'description' => 'Stock units, conversions, and packaging definitions.',
                    'icon' => 'switch-horizontal',
                    'keywords' => ['unit', 'measure', 'uom', 'conversion', 'packaging'],
                    'link' => ['type' => 'route', 'name' => 'admin.master-data.index'],
                ],
                [
                    'id' => 'stock-policies',
                    'title' => 'Stock Policies',
                    'description' => 'Configure inventory controls, valuation, and movement rules.',
                    'icon' => 'cube',
                    'keywords' => ['stock', 'inventory', 'valuation', 'movement', 'policy'],
                    'link' => ['type' => 'settings', 'section' => 'inventory'],
                    'status' => ['type' => 'registry', 'section' => 'inventory'],
                ],
                [
                    'id' => 'reorder-rules',
                    'title' => 'Reorder Rules',
                    'description' => 'Minimum stock levels, reorder points, and replenishment alerts.',
                    'icon' => 'bell',
                    'keywords' => ['reorder', 'minimum stock', 'replenishment', 'alert'],
                    'link' => ['type' => 'settings', 'section' => 'inventory'],
                    'status' => ['type' => 'registry', 'section' => 'inventory'],
                ],
                [
                    'id' => 'inventory-approvals',
                    'title' => 'Inventory Approvals',
                    'description' => 'Approval rules for stock adjustments and write-offs.',
                    'icon' => 'shield-check',
                    'keywords' => ['inventory', 'approval', 'adjustment', 'write-off', 'stock'],
                    'link' => ['type' => 'route', 'name' => 'admin.settings.approvals.index'],
                    'status' => ['type' => 'approvals'],
                ],
            ],
        ],

        'procurement' => [
            'label' => 'Procurement',
            'description' => 'Supplier management and purchasing controls.',
            'cards' => [
                [
                    'id' => 'suppliers',
                    'title' => 'Suppliers',
                    'description' => 'Vendor master data, contacts, and supply categories.',
                    'icon' => 'truck',
                    'keywords' => ['supplier', 'vendor', 'procurement', 'purchase'],
                    'link' => ['type' => 'route', 'name' => 'admin.procurement.vendors.index'],
                    'status' => ['type' => 'vendors'],
                ],
                [
                    'id' => 'purchase-rules',
                    'title' => 'Purchase Rules',
                    'description' => 'Purchase order defaults, limits, and authorization rules.',
                    'icon' => 'shopping-bag',
                    'keywords' => ['purchase', 'po', 'procurement', 'order rules'],
                    'coming_soon' => true,
                ],
                [
                    'id' => 'vendor-approvals',
                    'title' => 'Vendor Approvals',
                    'description' => 'Approval thresholds for vendor onboarding and purchases.',
                    'icon' => 'badge-check',
                    'keywords' => ['vendor', 'approval', 'onboarding', 'purchase'],
                    'coming_soon' => true,
                ],
                [
                    'id' => 'approval-chains',
                    'title' => 'Approval Chains',
                    'description' => 'Multi-level approval paths for procurement documents.',
                    'icon' => 'switch-horizontal',
                    'keywords' => ['approval chain', 'workflow', 'procurement', 'sign-off'],
                    'coming_soon' => true,
                ],
                [
                    'id' => 'vendor-evaluation',
                    'title' => 'Vendor Evaluation',
                    'description' => 'Supplier scorecards, performance metrics, and review cycles.',
                    'icon' => 'chart-pie',
                    'keywords' => ['vendor', 'evaluation', 'scorecard', 'performance'],
                    'coming_soon' => true,
                ],
            ],
        ],

        'finance' => [
            'label' => 'Finance',
            'description' => 'Accounting defaults, tax, and financial structure.',
            'cards' => [
                [
                    'id' => 'currency',
                    'title' => 'Currency',
                    'description' => 'Default currency and exchange handling for transactions.',
                    'icon' => 'currency-dollar',
                    'keywords' => ['currency', 'exchange', 'money', 'kes', 'usd'],
                    'link' => ['type' => 'settings', 'section' => 'company'],
                    'status' => ['type' => 'registry', 'section' => 'company'],
                ],
                [
                    'id' => 'taxes',
                    'title' => 'Taxes',
                    'description' => 'Tax rates, VAT defaults, and tax treatment on documents.',
                    'icon' => 'receipt-tax',
                    'keywords' => ['tax', 'vat', 'rate', 'levy'],
                    'link' => ['type' => 'settings', 'section' => 'company'],
                    'status' => ['type' => 'registry', 'section' => 'company'],
                ],
                [
                    'id' => 'payment-terms',
                    'title' => 'Payment Terms',
                    'description' => 'Standard payment terms applied to sales and billing.',
                    'icon' => 'credit-card',
                    'keywords' => ['payment', 'terms', 'net 30', 'credit', 'due'],
                    'link' => ['type' => 'settings', 'section' => 'company'],
                    'status' => ['type' => 'registry', 'section' => 'company'],
                ],
                [
                    'id' => 'chart-of-accounts',
                    'title' => 'Chart of Accounts',
                    'description' => 'General ledger accounts and posting structure.',
                    'icon' => 'book-open',
                    'keywords' => ['chart of accounts', 'gl', 'ledger', 'accounting'],
                    'link' => ['type' => 'route', 'name' => 'admin.accounting.accounts.index'],
                    'permission' => 'accounting.chart.view',
                ],
                [
                    'id' => 'cost-centers',
                    'title' => 'Cost Centers',
                    'description' => 'Manage costing dimensions used in production and accounting.',
                    'icon' => 'chart-pie',
                    'keywords' => ['cost center', 'dimension', 'costing', 'accounting'],
                    'coming_soon' => true,
                ],
                [
                    'id' => 'fiscal-years',
                    'title' => 'Fiscal Years',
                    'description' => 'Fiscal calendar, period closing, and year-end controls.',
                    'icon' => 'calendar',
                    'keywords' => ['fiscal', 'year', 'period', 'closing', 'calendar'],
                    'link' => ['type' => 'route', 'name' => 'admin.accounting.periods.index'],
                    'permission' => 'accounting.periods.view',
                ],
            ],
        ],

        'system' => [
            'label' => 'System',
            'description' => 'Platform configuration, integrations, and audit controls.',
            'cards' => [
                [
                    'id' => 'forms',
                    'title' => 'Forms',
                    'description' => 'Field visibility, requirements, and defaults per module.',
                    'icon' => 'clipboard-list',
                    'keywords' => ['form', 'field', 'layout', 'required', 'visible'],
                    'link' => ['type' => 'route', 'name' => 'admin.settings.forms.index'],
                    'status' => ['type' => 'forms'],
                ],
                [
                    'id' => 'notifications',
                    'title' => 'Notifications',
                    'description' => 'Email, SMS, and in-app notification preferences.',
                    'icon' => 'bell',
                    'keywords' => ['notification', 'email', 'sms', 'alert'],
                    'link' => ['type' => 'route', 'name' => 'admin.communications.notifications.index'],
                    'permission' => 'communications.notifications.view',
                ],
                [
                    'id' => 'approvals',
                    'title' => 'Approvals',
                    'description' => 'Discount, quotation, and operational approval thresholds.',
                    'icon' => 'shield-check',
                    'keywords' => ['approval', 'threshold', 'sign-off', 'authorization'],
                    'link' => ['type' => 'route', 'name' => 'admin.settings.approvals.index'],
                    'status' => ['type' => 'approvals'],
                ],
                [
                    'id' => 'numbering',
                    'title' => 'Numbering',
                    'description' => 'Manage document numbering for quotations, jobs, invoices, and inventory.',
                    'icon' => 'template',
                    'keywords' => ['numbering', 'sequence', 'prefix', 'document', 'invoice', 'quote'],
                    'link' => ['type' => 'route', 'name' => 'admin.settings.numbering.index'],
                    'status' => ['type' => 'numbering'],
                ],
                [
                    'id' => 'audit-settings',
                    'title' => 'Audit Settings',
                    'description' => 'Activity logging, retention, and compliance audit controls.',
                    'icon' => 'clock',
                    'keywords' => ['audit', 'log', 'compliance', 'retention', 'activity'],
                    'coming_soon' => true,
                ],
                [
                    'id' => 'integrations',
                    'title' => 'Integrations',
                    'description' => 'Third-party connectors, webhooks, and external services.',
                    'icon' => 'switch-horizontal',
                    'keywords' => ['integration', 'connector', 'webhook', 'api'],
                    'coming_soon' => true,
                ],
                [
                    'id' => 'api-settings',
                    'title' => 'API Settings',
                    'description' => 'API keys, access tokens, and developer integration settings.',
                    'icon' => 'key',
                    'keywords' => ['api', 'token', 'developer', 'integration'],
                    'coming_soon' => true,
                ],
                [
                    'id' => 'company-email',
                    'title' => 'Company Email',
                    'description' => 'Create and manage company mailboxes through cPanel from the dashboard.',
                    'icon' => 'inbox',
                    'keywords' => ['email', 'mailbox', 'cpanel', 'company', 'corporate'],
                    'link' => ['type' => 'route', 'name' => 'admin.settings.company-email.index'],
                    'status' => ['type' => 'company_email'],
                ],
            ],
        ],

    ],

];
