<?php

/**
 * Website CMS registry — additive metadata for admin media slots and settings.
 * Does not replace config/public-images.php, config/site.php, or config/conversion.php.
 */
return [

    'media_slots' => [
        'cards' => ['section' => 'hero', 'label' => 'Business Cards', 'image_key' => 'cards', 'alt' => 'Premium business cards', 'sort_order' => 10],
        'brochure' => ['section' => 'hero', 'label' => 'Brochures', 'image_key' => 'brochure', 'alt' => 'Professional brochures', 'sort_order' => 20],
        'packaging' => ['section' => 'hero', 'label' => 'Packaging', 'image_key' => 'packaging', 'alt' => 'Custom packaging', 'sort_order' => 30],
        'banner' => ['section' => 'hero', 'label' => 'Roll-Up Banners', 'image_key' => 'banner', 'alt' => 'Roll-up banners', 'sort_order' => 40],
        'stationery' => ['section' => 'hero', 'label' => 'Corporate Stationery', 'image_key' => 'stationery', 'alt' => 'Corporate stationery', 'sort_order' => 50],
        'merchandise' => ['section' => 'hero', 'label' => 'Branded Merchandise', 'image_key' => 'merchandise', 'alt' => 'Branded merchandise', 'sort_order' => 60],
        'print_press' => ['section' => 'hero', 'label' => 'Large Format Prints', 'image_key' => 'print_press', 'alt' => 'Large format prints', 'sort_order' => 70],

        'vehicle' => ['section' => 'services', 'label' => 'Vehicle Branding', 'image_key' => 'vehicle', 'alt' => 'Vehicle branding service', 'sort_order' => 10],
        'flyers' => ['section' => 'services', 'label' => 'Flyers', 'image_key' => 'flyers', 'alt' => 'Flyer printing', 'sort_order' => 20],
        'signage' => ['section' => 'services', 'label' => 'Signage', 'image_key' => 'signage', 'alt' => 'Signage printing', 'sort_order' => 30],

        'production_floor' => ['section' => 'facility', 'label' => 'Production Floor', 'image_key' => 'production_floor', 'alt' => 'Production floor', 'sort_order' => 10],
        'prepress' => ['section' => 'facility', 'label' => 'Pre-Press', 'image_key' => 'prepress', 'alt' => 'Pre-press department', 'sort_order' => 20],
        'finishing' => ['section' => 'facility', 'label' => 'Finishing', 'image_key' => 'finishing', 'alt' => 'Finishing operations', 'sort_order' => 30],
        'delivery' => ['section' => 'facility', 'label' => 'Dispatch & Delivery', 'image_key' => 'delivery', 'alt' => 'Dispatch and delivery', 'sort_order' => 40],
        'artwork' => ['section' => 'facility', 'label' => 'Artwork Review', 'image_key' => 'artwork', 'alt' => 'Artwork review', 'sort_order' => 50],
        'hero' => ['section' => 'facility', 'label' => 'Production Hero', 'image_key' => 'hero', 'alt' => 'Production floor hero', 'sort_order' => 60],

        'team.management' => ['section' => 'team', 'label' => 'Management Team', 'fallback_path' => '/images/storefront/team/management.jpg', 'alt' => 'Management team', 'sort_order' => 10],
        'team.design' => ['section' => 'team', 'label' => 'Design Team', 'fallback_path' => '/images/storefront/team/design.jpg', 'alt' => 'Design team', 'sort_order' => 20],
        'team.production' => ['section' => 'team', 'label' => 'Production Team', 'fallback_path' => '/images/storefront/team/production.jpg', 'alt' => 'Production team', 'sort_order' => 30],
        'team.quality' => ['section' => 'team', 'label' => 'Quality Team', 'fallback_path' => '/images/storefront/quality/color.jpg', 'alt' => 'Quality team', 'sort_order' => 40],
        'team.support' => ['section' => 'team', 'label' => 'Customer Support', 'fallback_path' => '/images/storefront/team/support.jpg', 'alt' => 'Customer support team', 'sort_order' => 50],
        'team.dispatch' => ['section' => 'team', 'label' => 'Delivery Team', 'fallback_path' => '/images/storefront/team/dispatch.jpg', 'alt' => 'Delivery team', 'sort_order' => 60],

        'quality.artwork' => ['section' => 'quality', 'label' => 'Artwork Approval', 'fallback_path' => '/images/storefront/quality/artwork.jpg', 'alt' => 'Artwork approval step', 'sort_order' => 10],
        'quality.prepress' => ['section' => 'quality', 'label' => 'Pre-Press Verification', 'fallback_path' => '/images/storefront/quality/prepress.jpg', 'alt' => 'Pre-press verification step', 'sort_order' => 20],
        'quality.color' => ['section' => 'quality', 'label' => 'Color Consistency', 'fallback_path' => '/images/storefront/quality/color.jpg', 'alt' => 'Color consistency check', 'sort_order' => 30],
        'quality.finishing' => ['section' => 'quality', 'label' => 'Finishing Inspection', 'fallback_path' => '/images/storefront/quality/finishing.jpg', 'alt' => 'Finishing inspection step', 'sort_order' => 40],
        'quality.packaging' => ['section' => 'quality', 'label' => 'Packaging Review', 'fallback_path' => '/images/storefront/quality/packaging.jpg', 'alt' => 'Packaging review step', 'sort_order' => 50],
        'quality.delivery' => ['section' => 'quality', 'label' => 'Delivery Confirmation', 'fallback_path' => '/images/storefront/quality/delivery.jpg', 'alt' => 'Delivery confirmation step', 'sort_order' => 60],

        'corporate' => ['section' => 'testimonials', 'label' => 'Corporate Testimonial', 'image_key' => 'corporate', 'alt' => 'Corporate client testimonial', 'sort_order' => 10],
        'school' => ['section' => 'testimonials', 'label' => 'School Testimonial', 'image_key' => 'school', 'alt' => 'School client testimonial', 'sort_order' => 20],
        'office' => ['section' => 'testimonials', 'label' => 'Office Testimonial', 'image_key' => 'office', 'alt' => 'Office client testimonial', 'sort_order' => 30],
        'team' => ['section' => 'testimonials', 'label' => 'Team Testimonial', 'image_key' => 'team', 'alt' => 'Team testimonial thumbnail', 'sort_order' => 40],
    ],

    'media_sections' => [
        'hero' => 'Hero Collage',
        'services' => 'Services & Products',
        'inside_jana' => 'Inside Jana Prints',
        'workflow' => 'Production Workflow',
        'facility' => 'Facility',
        'team' => 'Team',
        'quality' => 'Quality Promise',
        'testimonials' => 'Testimonials',
        'gallery_preview' => 'Recent Work Preview (Static Fallbacks)',
        'branding' => 'Branding Reference',
        'cta' => 'CTA & Conversion',
    ],

    'settings_admin_tabs' => [
        'footer' => 'Footer',
        'contact' => 'Contact',
        'whatsapp' => 'WhatsApp',
        'map' => 'Map',
        'social' => 'Social Links',
        'seo' => 'SEO Basics',
    ],

    'settings' => [
        'footer.tagline' => [
            'group' => 'footer',
            'type' => 'string',
            'admin_tab' => 'footer',
            'admin_pages' => ['footer-contact'],
            'label' => 'Footer Description',
            'description' => 'Company description shown in the site footer.',
            'fallback_config' => 'site.footer.tagline',
        ],
        'footer.nav' => [
            'group' => 'footer',
            'type' => 'json',
            'admin_tab' => 'footer',
            'admin_pages' => ['footer-contact'],
            'label' => 'Footer Navigation Links',
            'description' => 'JSON array of {label, href} navigation links.',
            'fallback_config' => 'site.footer.nav',
        ],
        'footer.trust_badges' => [
            'group' => 'footer',
            'type' => 'json',
            'admin_tab' => 'footer',
            'admin_pages' => ['footer-contact'],
            'label' => 'Trust Badges',
            'description' => 'JSON array of badge label strings.',
            'fallback_config' => 'site.footer.trust_badges',
        ],
        'footer.social' => [
            'group' => 'footer',
            'type' => 'json',
            'admin_tab' => 'footer',
            'admin_pages' => ['footer-contact'],
            'label' => 'Social Links (Advanced JSON)',
            'description' => 'JSON array of {label, href, icon} objects. Individual platform URLs in the Social tab override matching icons.',
            'fallback_config' => 'site.footer.social',
        ],
        'footer.copyright' => [
            'group' => 'footer',
            'type' => 'string',
            'admin_tab' => 'footer',
            'admin_pages' => ['footer-contact'],
            'label' => 'Copyright Line',
            'description' => 'Copyright text shown in the footer. Use {year} for the current year.',
        ],
        'footer.location_suffix' => [
            'group' => 'footer',
            'type' => 'string',
            'admin_tab' => 'footer',
            'admin_pages' => ['footer-contact'],
            'label' => 'Footer Location Suffix',
            'description' => 'Location text shown beside the site tagline in the footer bar.',
        ],
        'social.facebook' => [
            'group' => 'footer',
            'type' => 'url',
            'admin_tab' => 'social',
            'admin_pages' => ['footer-contact'],
            'optional' => true,
            'label' => 'Facebook URL',
            'description' => 'Facebook profile or page URL. Leave empty to hide or use JSON fallback.',
        ],
        'social.instagram' => [
            'group' => 'footer',
            'type' => 'url',
            'admin_tab' => 'social',
            'admin_pages' => ['footer-contact'],
            'optional' => true,
            'label' => 'Instagram URL',
            'description' => 'Instagram profile URL. Leave empty to hide or use JSON fallback.',
        ],
        'social.linkedin' => [
            'group' => 'footer',
            'type' => 'url',
            'admin_tab' => 'social',
            'admin_pages' => ['footer-contact'],
            'optional' => true,
            'label' => 'LinkedIn URL',
            'description' => 'LinkedIn company or profile URL.',
        ],
        'social.twitter' => [
            'group' => 'footer',
            'type' => 'url',
            'admin_tab' => 'social',
            'admin_pages' => ['footer-contact'],
            'optional' => true,
            'label' => 'Twitter / X URL',
            'description' => 'Twitter / X profile URL.',
        ],
        'contact.phone' => [
            'group' => 'contact',
            'type' => 'phone',
            'admin_tab' => 'contact',
            'admin_pages' => ['footer-contact'],
            'label' => 'Phone Number',
            'description' => 'Displayed contact phone number.',
            'fallback_config' => 'conversion.contact.phone',
        ],
        'contact.phone_href' => [
            'group' => 'contact',
            'type' => 'string',
            'admin_tab' => 'contact',
            'admin_pages' => ['footer-contact'],
            'optional' => true,
            'label' => 'Phone Link (optional)',
            'description' => 'Leave blank to auto-generate tel: link from the phone number above.',
            'fallback_config' => 'conversion.contact.phone_href',
        ],
        'contact.email' => [
            'group' => 'contact',
            'type' => 'email',
            'admin_tab' => 'contact',
            'admin_pages' => ['footer-contact'],
            'label' => 'Email Address',
            'description' => 'Displayed contact email.',
            'fallback_config' => 'conversion.contact.email',
        ],
        'contact.email_href' => [
            'group' => 'contact',
            'type' => 'string',
            'admin_tab' => 'contact',
            'admin_pages' => ['footer-contact'],
            'optional' => true,
            'label' => 'Email Link (optional)',
            'description' => 'Leave blank to auto-generate mailto: link from the email address above.',
            'fallback_config' => 'conversion.contact.email_href',
        ],
        'contact.address' => [
            'group' => 'contact',
            'type' => 'string',
            'admin_tab' => 'contact',
            'admin_pages' => ['footer-contact'],
            'label' => 'Address',
            'description' => 'Physical address shown in footer and contact.',
            'fallback_config' => 'conversion.contact.address',
        ],
        'contact.address_detail' => [
            'group' => 'contact',
            'type' => 'string',
            'admin_tab' => 'contact',
            'admin_pages' => ['footer-contact'],
            'optional' => true,
            'label' => 'Address Detail',
            'description' => 'Optional secondary address line on the contact section.',
            'fallback_config' => 'conversion.contact.address_detail',
        ],
        'contact.hours' => [
            'group' => 'contact',
            'type' => 'string',
            'admin_tab' => 'contact',
            'admin_pages' => ['footer-contact'],
            'label' => 'Weekday Business Hours',
            'description' => 'Business hours Monday to Friday.',
            'fallback_config' => 'conversion.contact.hours',
        ],
        'contact.hours_weekend' => [
            'group' => 'contact',
            'type' => 'string',
            'admin_tab' => 'contact',
            'admin_pages' => ['footer-contact'],
            'label' => 'Weekend Business Hours',
            'description' => 'Saturday business hours.',
            'fallback_config' => 'conversion.contact.hours_weekend',
        ],
        'contact.map_enabled' => [
            'group' => 'contact',
            'type' => 'boolean',
            'admin_tab' => 'map',
            'admin_pages' => ['footer-contact'],
            'label' => 'Enable Map',
            'description' => 'When disabled, the contact page shows a compact location card instead of an embedded map.',
            'fallback_config' => 'conversion.contact.map_enabled',
        ],
        'contact.map_latitude' => [
            'group' => 'contact',
            'type' => 'string',
            'admin_tab' => 'map',
            'admin_pages' => ['footer-contact'],
            'label' => 'Map Latitude',
            'description' => 'Google Maps embed latitude.',
            'fallback_config' => 'conversion.contact.map_latitude',
        ],
        'contact.map_longitude' => [
            'group' => 'contact',
            'type' => 'string',
            'admin_tab' => 'map',
            'admin_pages' => ['footer-contact'],
            'label' => 'Map Longitude',
            'description' => 'Google Maps embed longitude.',
            'fallback_config' => 'conversion.contact.map_longitude',
        ],
        'contact.map_zoom' => [
            'group' => 'contact',
            'type' => 'string',
            'admin_tab' => 'map',
            'admin_pages' => ['footer-contact'],
            'label' => 'Map Zoom Level',
            'description' => 'Google Maps embed zoom level.',
            'fallback_config' => 'conversion.contact.map_zoom',
        ],
        'contact.map_url' => [
            'group' => 'contact',
            'type' => 'url',
            'admin_tab' => 'map',
            'admin_pages' => ['footer-contact'],
            'optional' => true,
            'label' => 'External Map URL',
            'description' => 'Link to open location in Google Maps.',
            'fallback_config' => 'conversion.contact.map_url',
        ],
        'contact.map_embed' => [
            'group' => 'contact',
            'type' => 'url',
            'admin_tab' => 'map',
            'admin_pages' => ['footer-contact'],
            'optional' => true,
            'label' => 'Map Embed URL',
            'description' => 'Google Maps iframe embed URL for the contact map.',
            'fallback_config' => 'conversion.contact.map_embed',
        ],
        'contact.map_placeholder' => [
            'group' => 'contact',
            'type' => 'string',
            'admin_tab' => 'map',
            'admin_pages' => ['footer-contact'],
            'optional' => true,
            'label' => 'Map Placeholder Label',
            'description' => 'Fallback map location label.',
            'fallback_config' => 'conversion.contact.map_placeholder',
        ],
        'whatsapp.number' => [
            'group' => 'contact',
            'type' => 'phone',
            'admin_tab' => 'whatsapp',
            'admin_pages' => ['footer-contact'],
            'label' => 'WhatsApp Number',
            'description' => 'WhatsApp number without plus sign prefix issues.',
            'fallback_config' => 'conversion.whatsapp.number',
        ],
        'whatsapp.message' => [
            'group' => 'contact',
            'type' => 'string',
            'admin_tab' => 'whatsapp',
            'admin_pages' => ['footer-contact'],
            'label' => 'WhatsApp Default Message',
            'description' => 'Pre-filled WhatsApp enquiry message.',
            'fallback_config' => 'conversion.whatsapp.message',
        ],
        'whatsapp.link' => [
            'group' => 'contact',
            'type' => 'url',
            'admin_tab' => 'whatsapp',
            'admin_pages' => ['footer-contact'],
            'optional' => true,
            'label' => 'WhatsApp Link (Optional)',
            'description' => 'Full wa.me link override. If empty, the link is generated from number and message.',
        ],
        'whatsapp.response_time' => [
            'group' => 'contact',
            'type' => 'string',
            'admin_tab' => 'whatsapp',
            'admin_pages' => ['footer-contact'],
            'label' => 'WhatsApp Response Time Label',
            'description' => 'Shown on the contact section WhatsApp card.',
            'fallback_config' => 'conversion.whatsapp.response_time',
        ],
        'site.name' => [
            'group' => 'seo',
            'type' => 'string',
            'admin_pages' => ['seo-global'],
            'label' => 'Site Name',
            'description' => 'Company name used in titles and copyright.',
            'fallback_config' => 'site.name',
        ],
        'site.tagline' => [
            'group' => 'seo',
            'type' => 'string',
            'admin_pages' => ['seo-global'],
            'label' => 'Site Tagline',
            'description' => 'Short tagline shown in footer bottom bar.',
            'fallback_config' => 'site.tagline',
        ],
        'seo.title' => [
            'group' => 'seo',
            'type' => 'string',
            'admin_tab' => 'seo',
            'admin_pages' => ['footer-contact', 'seo-global'],
            'label' => 'Default SEO Title',
            'description' => 'Default page title for search engines.',
            'fallback_config' => 'site.seo.title',
        ],
        'seo.description' => [
            'group' => 'seo',
            'type' => 'string',
            'admin_tab' => 'seo',
            'admin_pages' => ['footer-contact', 'seo-global'],
            'label' => 'Default Meta Description',
            'description' => 'Default meta description for search engines.',
            'fallback_config' => 'site.seo.description',
        ],
        'seo.keywords' => [
            'group' => 'seo',
            'type' => 'string',
            'admin_pages' => ['seo-global'],
            'label' => 'Meta Keywords',
            'description' => 'Comma-separated SEO keywords.',
            'fallback_config' => 'site.seo.keywords',
        ],
        'seo.og_image' => [
            'group' => 'seo',
            'type' => 'string',
            'admin_tab' => 'seo',
            'admin_pages' => ['footer-contact', 'seo-global'],
            'label' => 'Open Graph Image Path',
            'description' => 'Default OG image path (relative to site root).',
            'fallback_config' => 'site.seo.og_image',
        ],
    ],

    'settings_groups' => [
        'footer' => 'Footer',
        'contact' => 'Contact & Map',
        'seo' => 'SEO & Global',
    ],

];
