<div class="jp-doc__footer">
    <p class="jp-doc__footer-thanks">{{ $documentFooter['thanks'] ?? __('Thank you for choosing Jana Prints.') }}</p>
    <p class="jp-doc__footer-system">{{ $documentFooter['system'] ?? __('This document was generated by Jana Prints ERP.') }}</p>
</div>
