<div class="jp-doc__footer">
    <p class="jp-doc__footer-thanks">{{ __('Thank you for choosing Jana Prints.') }}</p>
    <p class="jp-doc__footer-system">{{ __('This document was generated by Jana Prints ERP.') }}</p>
</div>
