@if (! empty($paymentFooter))
    <div class="jp-doc__payment-footer">
        <table class="jp-doc__payment-footer-table" cellpadding="0" cellspacing="0">
            <tr>
                <td class="jp-doc__payment-footer-left">
                    <p class="jp-doc__payment-footer-title">{{ __('Payment Details') }}:</p>
                    @foreach ($paymentFooter as $line)
                        <p class="jp-doc__payment-footer-line">{{ $line }}</p>
                    @endforeach
                </td>
                <td class="jp-doc__payment-footer-right">
                    <p class="jp-doc__footer-thanks">{{ $documentFooter['thanks'] ?? __('Thank you for choosing Jana Prints.') }}</p>
                    <p class="jp-doc__footer-system">{{ $documentFooter['system'] ?? __('This document was generated by Jana Prints ERP.') }}</p>
                </td>
            </tr>
        </table>
    </div>
@endif
